### ISSUE TITLE
Темизация календаря

### ISSUE THREAD

**Issue by edbond88** [t1m0n/air-datepicker#1]
Я хочу сам поменять дизайн календаря, но не хочу лезть в файл datepicker.min.css т.к. я его подключаю бауэром и не хочется лезть в него. Так же у меня несколько различных визуально календарей.
Если бы была возможность добавить класс к обертке календаря, то это было бы круто и помогло бы мне его изменить.

Хотя может я где-то не заметил в доках, и все-таки есть такая возможность.

**Comment by t1m0n** [comment]
Согласен, добавлю в 1.1.0.

**Comment by t1m0n** [comment]
Залил новую версию. Чтобы добавить дополнительные классы используйте опцию `classes`:

```JavaScript
$('#datepicker').datepicker({
     classes: 'my custom classes'
})
```
