### ISSUE TITLE
compatiblity browser

### ISSUE THREAD

**Issue by usb248** [t1m0n/air-datepicker#10]
Hi,

 Any compatibility polyfill for IE9 ?

**Comment by t1m0n** [comment]
Hi,
I don't plan to add compatibility for old browsers, but I think it should work in IE9. You just need to add extra styles to make it look better. Try to use `{float:left}` instead of `flexbox` on cells and other ui elements.

**Comment by t1m0n** [comment]
Closed due to inactivity
