### ISSUE TITLE
Input data are deleted, to instantiate object again, content load via ajax.

### ISSUE THREAD

**Issue by inferno7291** [t1m0n/air-datepicker#101]
I have a form that contains 2 parts one fixed and one that is created by Ajax.
New form:
• When filling the input by hand and then charge the other party by Ajax form input type date content is deleted, if not fill the input from the calendar.
Edit form data fields are already filled by PHP:
• I make an issue that causes a portion of the form is refreshed by Ajax, all fields type date are deleted.

**I understand that is a bug because when instantiated the object datepicker would not eliminate the value they have already allocated**

Function, so it's easier if you then have to re-instantiate, because a part of the content is loaded via ajax:
```
function loadCalendar(){
    /**
     * Crear diferentes calendarios
     */
    $('.calendario').datepicker({
        language: 'es',
        todayButton: new Date(),
        autoClose: true,
        clearButton: true,
    });
    $('.calendario-time').datepicker({
        language: 'es',
        timepicker: true,
        todayButton: new Date(),
        autoClose: true,
        clearButton: true
    });

    $('.only-time').datepicker({
        dateFormat: ' ',
        timepicker: true,
        classes: 'only-timepicker'
    });
    //Quitar el espacio que genera el calendario
    //a la izquierda cuando es solo de tiempo
    $('.only-time').on('focusout',function(){
        $(this).val($.trim($(this).val()));
    })
}
```

This is the part of the form is loaded using Ajax.
```
$('.selectDelegacion.showHl').on('change',function(){
        if($(this).val() != 0){
            $.get('url_to_page',{showWorkingHours:1, d:$(this).val()})
            .done(function(result){
                $('.horarioLaboralShow').empty().append(result);
                loadCalendar();
            })
        }else{
            $('.horarioLaboralShow').empty();
        }
    });
```

Sorry for my English, Google Translate
Thanks for your time

**Comment by t1m0n** [comment]
Could you provide an example or jsfiddle of what you are trying to do? Actually I don't sure if datepicker works well with `<input type="date" />`.

**Comment by inferno7291** [comment]
Here is the example: https://jsfiddle.net/21nusrwc/

**Comment by t1m0n** [comment]
So input value is cleared after another datepicker instance is inited on it? Unfortunately there is no 'good' way to do it now, because currently user's hand input doesn't parsed by the plugin. As temporary workaround I suggest you to use `selectDate` method to select desirable dates on init - https://jsfiddle.net/g0dzgto0/
