### ISSUE TITLE
only-timepicker with confirm button

### ISSUE THREAD

**Issue by eddbs** [t1m0n/air-datepicker#102]
Hello Timofey, could you please tell me how to add a custom button to send the time of the time picker to the input? 
![onlytimepicker](https://cloud.githubusercontent.com/assets/12954744/17619451/5bcbe5de-603a-11e6-9e68-4cf32f0f744b.png)
I made some code changes and add that button but now I don't know how to send the time shown on the picker to the input field.

And also is there a way to avoid to have this blank space? 
![onlytimepickercode](https://cloud.githubusercontent.com/assets/12954744/17619539/cc228900-603a-11e6-86db-f7f7a1a540d4.png) ![blnkspacebug](https://cloud.githubusercontent.com/assets/12954744/17619808/ae72f0b4-603c-11e6-8292-a448d213429d.png)
maybe changing something for send null or false or something like that? this would show the time properly like "hh:ii aa" instead of  "  hh:ii:aa" on the input.

And only one thing more... I've found a bug, the slider doesn't starts on the correct position when the format is set to 12hrs instead of 24hrs.
![slider bug](https://cloud.githubusercontent.com/assets/12954744/17619888/34d006b0-603d-11e6-9abc-ae8fad1558c1.png)
and when I move the slider the "PM" changes to "AM", the slider should starts from the 20hr position.

..And congratulations for your amazing work on this calendar, it's the best one of all, I love the design and it's functions, for real! .. Thank you!

**Comment by t1m0n** [comment]
Hello, thanks for your response! 
For filling in input, you can use `selectDate` method.
Currently there is no proper way to delete space at beginning of the string, you can remove it manually after value is changed. I think I'll add 'only timepicker` feature in next release, so it would be fixed there

**Comment by ADmad** [comment]
> I think I'll add 'only timepicker` feature in next release, so it would be fixed there 

:+1:

**Comment by eddbs** [comment]
Hello, thank you for your support! , I'll definitely LOVE to see "only time picker" feature in next release! :D

**Comment by ibnbay99** [comment]
@eddbs , how to add confirm button like yours?
Or all how can tell how to do it with this plugin

**Comment by andrei930** [comment]
@ibnbay99 Here's a quick jQuery snippet that will add a confirm button if you already have the clear button enabled:
`
            var okButton = '<span class="datepicker--button" data-action="hide">Ok</span>';
            $('.datepicker--button[data-action="clear"]').each(function( index ) {
                $(okButton).insertBefore($(this));
            });  
`
