### ISSUE TITLE
Faulty month name with hungarian locale

### ISSUE THREAD

**Issue by tiborsaas** [t1m0n/air-datepicker#103]
Very strange, only for march in hungarian it displays "MÁRÁRCIUS" instead of Március. I've checked in the locale file and it's normal there.

![image](https://cloud.githubusercontent.com/assets/342688/17686174/8a42deb2-636a-11e6-9e37-bbd40ae95e7a.png)

**Comment by tiborsaas** [comment]
If I change it to lowercase "március" in the local file, it works as expected. Strange...

**Comment by t1m0n** [comment]
Already exists one #92 and already fixed in `develop` branch, you can use it now as temporary decision. It happens because of bug in method which compiles abbreviations, like `MM`, to full month name and others.
