### ISSUE TITLE
Range click behaviour changed between versions

### ISSUE THREAD

**Issue by johnknoop** [t1m0n/air-datepicker#105]
Before we upgraded to 2.1.0, when a range was selected, the user could tweak the range by clicking on one of the end dates. The datepicker would then go into a state where the other end date was still selected. This was very convenient when a range spans over two months, and you just want to change the start OR or end date.

Is there any setting that might bring this behaviour back?

**Comment by t1m0n** [comment]
Yeah, I'm totally agree with you. But this feature has been removed due to opportunity of selecting single date in range mode... Actually I think it could be restored in cases when two dates are selected (I don't remember what problems could appear though), will see what can be done.
