### ISSUE TITLE
Addition onBeforeShow event + select date inserted from input

### ISSUE THREAD

**Issue by gxenakis** [t1m0n/air-datepicker#109]
at main js file :
`// events`
`			onBeforeShow: '',`
find below and add:
`show: function () {`
`            this.opts.onBeforeShow(this);`

on calling :
`onBeforeShow: function(inst) {`
`        				if (inst.elIsInput && $(inst.el).val() != ''){`
`                //sets date from input`
`                					var $selDate = parseDateFromInput($(inst.el).val());`
`                					inst.selectDate($selDate);`
`        				}`
`			}`

**Comment by deyanspasov** [comment]
Great! Thank you @gxenakis this really help me and save me a lot of time 👍

**Comment by t1m0n** [comment]
You could use `onShow` and `onHide` events since version 2.2.0.
