### ISSUE TITLE
how to custom disable date(array) ?

### ISSUE THREAD

**Issue by chanalaaa** [t1m0n/air-datepicker#11]
![screenshot 5](https://cloud.githubusercontent.com/assets/12951693/12572022/7c8de2f8-c419-11e5-9ba3-ddd4c0c6faaf.png)

thanks : )

**Comment by chanalaaa** [comment]
var disabledDays = new Date([2016,01,10],[2016,01,13])

**Comment by t1m0n** [comment]
You can use `onRenderCell` option to disable or modify cells, see example http://t1m0n.name/air-datepicker/docs/#example-disabled-days.

**Comment by t1m0n** [comment]
Closed due to inactivity

**Comment by bantawa04** [comment]
How can we disable selecting past dates ??

**Comment by nishadtu** [comment]
Hi, 

I want to enable only one or two days. Other dates should be disabled. Is it possible?

**Comment by TammyTee** [comment]
> How can we disable selecting past dates ??

In case anyone else is looking for an answer to @bantawa04 's question, you have to set the `minDate` option when you initialize.

http://t1m0n.name/air-datepicker/docs/#sub-section-24

```
$('#disabled-days').datepicker({
  ...

  // all dates before the current day will be disabled
  minDate: new Date()
});
```
