### ISSUE TITLE
How to show 2 months for for inline?

### ISSUE THREAD

**Issue by keem1201** [t1m0n/air-datepicker#115]
How to show 2 months for for inline in stead of 1 month?

And also, how to set minute increment; for example 15 minutes?

Thanks

**Comment by t1m0n** [comment]
There is no option for showing multiple months currently, so you can't ( 
For minutes, there is `minutesStep` option, if you'll set it to `15` then it should change 15 minutes per one time.

**Comment by keem1201** [comment]
It is possible to have an option for showing multiple months soon?

**Comment by t1m0n** [comment]
I don't have much time now to develop this feature, so I think it will be not soon.

**Comment by loginetsolutions** [comment]
+1 Really this is the only option I missed. Kudos for this excellent work!
