### ISSUE TITLE
Yii2 jQuery 2.2.x conflict :(

### ISSUE THREAD

**Issue by adamasantares** [t1m0n/air-datepicker#118]
Возможно ли использовать последнюю версию не с jQuery 3.0.0, а с 2.2.x? Возникает конфликт версий в yii2. Ставится версия air-dp максимум 2.0.2, но в нем нет событий onShow и тд.

Не смог найти в коде, где именно зависимость от третьей версии jquery

**Comment by t1m0n** [comment]
Я думаю не должно возникнуть никаких проблем при использовании плагина со старыми версиями jQuery. Третья версия используется просто потому что она последняя, никаких зависимостей от новых методов нет (некоторые пользователи жаловались на старую версию).

Видимо придется в ручную как-то добавлять плагин, если честно никогда не работал с yii, поэтому не могу ничего дельного сказать.

Если, к примеру, устанавливать через `npm` то можно в `package.json` указать нужную версию:
```javascript
{
  "dependencies": {
    "air-datepicker": "latest",
    "jquery": "2.2.x"
  }
}
```

**Comment by adamasantares** [comment]
я пробовал вручную, не вышло. Composer видит, что в bower.json прописано

```
"dependencies": {
    "jquery": "^3.0.0"
  }
```

и вываливает ошибку. Раз от версии 3.0.0 нет реальной зависимости, то можешь поменять на "^2.0.0"? Чтобы в bower обновилась запись о пакете. Вручную копировать не очень здорово, тогда лишаешься обновлений.

ммм? :)

**Comment by t1m0n** [comment]
Обновил версию на диапазон от 2 до <4, думаю должно помочь.

**Comment by adamasantares** [comment]
Спасибо! Попробуем
