### ISSUE TITLE
Double calendars

### ISSUE THREAD

**Issue by tommiehansen** [t1m0n/air-datepicker#121]
Any possibility for you to add an option to have a multi-calendar view ie 2 calenderas visible at the same time? Often when picking a range of dates this is often preferred since often date1 and date2 can be in two different months.

**Comment by t1m0n** [comment]
Yeah I'm planning to add this feature, but I think it will not be very soon, due to time deficit.

duplicate of #8.

**Comment by wuliqiangqiang** [comment]
@t1m0n hi，was it added about the range can set two calendars view?

**Comment by t1m0n** [comment]
@wuliqiangqiang you could try to use version from [this ](https://github.com/t1m0n/air-datepicker/tree/multiple-cals )branch. It is not completed, but basic functionality should work.
