### ISSUE TITLE
Double-click on date not working when pulled from NPM

### ISSUE THREAD

**Issue by johnknoop** [t1m0n/air-datepicker#122]
Hi

The feature that was added in 2.2.0 (clicking twice on the same date) works great when downloading the dist file from github, but when we pull that version from NPM, it seems to lack this behaviour.

/john

**Comment by t1m0n** [comment]
Hi! I've just installed v2.2.0 from NPM, and it seems to work fine. What feature do you mean?

**Comment by johnknoop** [comment]
The feature you introduced in version 2.2.0, i.e. when in range mode, clicking twice on the same date will create a range between those two same dates. When I pull it from NPM, the second click clears the selection.

**Comment by t1m0n** [comment]
Since `v2.2.0` you should set `{toggleSelected: false}` to be able to create range on same date.

**Comment by johnknoop** [comment]
Ah! Thanks.
