### ISSUE TITLE
nav arrows disabled when they should not be, min and max dates specified

### ISSUE THREAD

**Issue by ps2goat** [t1m0n/air-datepicker#123]
We currently have these settings, using an older version of the airdatepicker circa January 26, 2016 (no version is listed in the file).  I have pulled down the latest npm package today (2.2.1) and I am still able to reproduce the issues.

I created a plunk to demonstrate the issue as easily as possible.  Basically, my min date is 1/31/2017 and my end date is 02/07/2017.  My navigation arrows are both disabled for some reason.  I would expect to be able to navigate from January (the month shown) to February, since I have a max date in February.

Without modifying the airdatepicker code directly, the only option I currently have (at work) is to make this option's value `false`:

`disableNavWhenOutOfRange`

However, that enables arrows that should not be enabled.

Here is the plunk:

http://plnkr.co/edit/Asp86O?p=preview

**Comment by t1m0n** [comment]
Thanks for the bug report, fixed in v2.2.2
