### ISSUE TITLE
navTitles doesn't work

### ISSUE THREAD

**Issue by fwh1990** [t1m0n/air-datepicker#124]
Hello, I use your project today, thanks very much.
When I set option navTitles, it doesn't work, the value is like "yyyy年MM", format fail. But if I set navTitles as "yyyy 年 MM", it works. The word is chinese.
Do you know what happen?

**Comment by t1m0n** [comment]
Hello! 
Try to wrap hieroglyph in `<span>`, it should help.

```javascript
$('#dp').datepicker({
    navTitles: {
        days: 'yyyy<span>年</span>MM'
    }
})
```

**Comment by fwh1990** [comment]
+1. Thanks a lot.
