### ISSUE TITLE
How i can set default Date in input value?..

### ISSUE THREAD

**Issue by musaev-haybulla** [t1m0n/air-datepicker#127]
I cannot set default value in input. This lib have this function?..

**Comment by t1m0n** [comment]
Currently you could just select desirable date after plugin initialization:

**HTML**
```html
<input type="text" id="dp"/>
```

**JS**
```javascript
var dp = $('#dp').datepicker().data('datepicker');

dp.selectDate(new Date());
```

**Comment by musaev-haybulla** [comment]
Thank you, it's work!

**Comment by musaev-haybulla** [comment]
I'm sorry, but i'm find a bug.
This code `dp.selectDate(new Date(2016, 09, 30)); ` set date in input 30.10.2016 (month +1) every time. How fix this?..

**Comment by t1m0n** [comment]
Month number starts from 0 in JS, so it will be 0 for January and 11 for December (and 9 for November). Please read docs reference on [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date)

**Comment by musaev-haybulla** [comment]
Thank you

**Comment by nicooprat** [comment]
Looks like there's a `startDate` option to set a default start value: http://t1m0n.name/air-datepicker/docs/#sub-section-6

No `endDate` though? `selectDate()` method triggers `onSelect` callback, and can cause infinite loop in my case. For now I'm using a `var first = true|false` to avoid this, but it's far from ideal...

Is there any plan to provide real default values? Or better, get them from the input field the plugin is bound to?

**Comment by t1m0n** [comment]
I'm afraid there is only one method to select start date - its to use `selectDate()`. I'm planning to include default feature to parse date from string, but can't say for sure when it will be done.

**Comment by create-account** [comment]
The `selectDate()`, since it triggers the `onSelect`, causes issues like @nicooprat  mentioned.
This means we would have to resort to multiple flag checks to see if the `onSelect` was trigger via 'actual' change of the date or via the 'selectDate()', when multiple instances of datepicker is used at a time in the same page.

**Comment by AshwinIcfGithub** [comment]
@t1m0n when i type date manually how to highlight that date in datepicker? Is there any inbuild feature? or should I update the datepicker manually?

**Comment by t1m0n** [comment]
@AshwinIcfGithub there is no built in feature, you have to handle it manually

**Comment by asifmai** [comment]
what if I have a date range selector? How do I set the initial value for that?

**Comment by nuwanchamp** [comment]
> what if I have a date range selector? How do I set the initial value for that?

I have faced this problem too
