### ISSUE TITLE
todayButton and clearButton does not work in IE11

### ISSUE THREAD

**Issue by yama** [t1m0n/air-datepicker#133]
todayButton and clearButton does not work in IE11 .
Sample code

```
var options = {
    todayButton   : new Date(),
    clearButton   : true,
};

jQuery('.DatePicker').datepicker(options);
```

**Comment by t1m0n** [comment]
Which version are you using? It should work fine in IE, you can check this [fiddle](https://jsfiddle.net/3teurff0/).

**Comment by yama** [comment]
Very thanks.
Cause was found. mootools has caused the conflict.
