### ISSUE TITLE
Inline Multiple Month support

### ISSUE THREAD

**Issue by pedrocortizo** [t1m0n/air-datepicker#134]
First of all, greeting for this magnific calendar @t1m0n 

Exists functionality to display inline multiple months? It is one of the few missing features to this magnificent calendar...

Thx for still coding for this excelent datepicker

**Comment by t1m0n** [comment]
Hello! Thanks for your response!
Unfortunately there is no such functionality now, but I hope I'll manage to add this feature in next releases. 
I'll close this issue due to duplicate of #8

**Comment by pedrocortizo** [comment]
Thank you...
Waiting for this feature
I hope you have time to do this development :)
