### ISSUE TITLE
error on webkit

### ISSUE THREAD

**Issue by blstdmi** [t1m0n/air-datepicker#154]
![default](https://cloud.githubusercontent.com/assets/16188904/20661836/d2350c92-b561-11e6-8aea-5732d2315f75.png)

jQuery.Deferred exception: 'undefined' is not a function (evaluating 'this._onSelectDate.bind(this)') undefined  jquery-3.1_1.js:3846
TypeError: 'undefined' is not a function (evaluating 'this._onSelectDate.bind(this)') datepicker.js:2202

what do?

**Comment by t1m0n** [comment]
When does this happen? Which version are you using? I can't reproduce this error.

**Comment by blstdmi** [comment]
i use what browser https://pawelmhm.github.io/python/pyqt/qt/webkit/2015/09/08/browser.html
