### ISSUE TITLE
set minHours and minMinutes from other timepicker

### ISSUE THREAD

**Issue by ibnbay99** [t1m0n/air-datepicker#157]
Hi, i want to set minHours and minMinutes from other timepicker.
Like this:
```
var newDate = new Date();
            var startHours = moment(newDate).format("H");
            var startMinutes = moment(newDate).format("m");
origin_start_time.datepicker({
                language: "id", position: "top left", timepicker: true, onlyTimepicker: true, timeFormat: 'hh:ii',
                clearButton: true, minHours: startHours, minMinutes: startMinutes,
                onSelect: function (fd, d, picker) {
                    if (!d) return;

                    endHours = d.getHours();
                    endMinutes = d.getMinutes();
                    newDate.setHours(d.getHours());
                    newDate.setMinutes(d.getMinutes());

                    origin_end_time.datepicker({minHours: endHours, minMinutes: endMinutes});
                },
                onHide: function (dp, animationCompleted) {
                    if (animationCompleted) {
                        setOriginTime(origin_start_time.val(), origin_end_time.val());
                    }
                }
            });
```
But if, like that it not natural set minimum for hours and minutes.
If first timepicker set to 10:59, the second timepicker must be minimum 11:59, can't 11:00...

Thanks

**Comment by t1m0n** [comment]
Hi, as I understand you want second datepicker has minimum time equal to the first datepicker selected date. If so try to use `minDate` instead of `minHours` and `minMinutes`. I've created example here https://jsfiddle.net/3huee5ru/

**Comment by ibnbay99** [comment]
Cool, it's work like a charm... Thanks @t1m0n  :+1:

**Comment by ibnbay99** [comment]
Hi @t1m0n , sorry I comment in closed issue. because it's still relevant.
I want to ask after I Choose first timepicker, the second timepicker it still display last time on my local.
But if i drag a hour or minute, the minimum is valid from first timepicker.

How to update the second timepicker on show event without change a time first?

Thanks

**Comment by t1m0n** [comment]
So you want to update second timepicker only when it start showing? If so, you just need to save first timepikcer's date and update second timepicker in `onShow` option. Heres example https://jsfiddle.net/800vg4LL/

**Comment by ibnbay99** [comment]
@t1m0n , sorry to bother u.
But your sample recently doesn't meet my need.

1. Select timepicker-1 (change the time)
![screenshot-1](https://cloud.githubusercontent.com/assets/21232045/21257660/e5627cca-c3ab-11e6-9ad8-53b00de312b8.png)
2. Select timepicker-2 (first show, but don't change the time)
![screenshot -2](https://cloud.githubusercontent.com/assets/21232045/21257689/09ae8542-c3ac-11e6-8273-2f75f0ae8898.png)

any hack for this thing?

**Comment by t1m0n** [comment]
Oh I've forgot to save changes in fiddle. Heres another one - https://jsfiddle.net/800vg4LL/1/
