### ISSUE TITLE
Why not English as primary language?

### ISSUE THREAD

**Issue by yoosuf** [t1m0n/air-datepicker#163]
I was trying to use this js component and i really didn't like the default language was Russian.  Why not make the default language as English and localization as optional?

**Comment by porthunt** [comment]
I think it is a little weird too. Took me a while to find out what was happening and my team classified as a bug. lol

**Comment by pmorch** [comment]
I guess we better get used to it. Chinese, not Russian is becoming the default in more and more code. So far, the code itself is in English, but I guess it won't be long before the source starts containing e.g.

    var 愛 = 12;

At least for now, none of the reserved words are in Chinese :-)

**Comment by porthunt** [comment]
Nope, not a bug. But the default on the web is English, therefore I understand his point. haha

**Comment by 2rohith2** [comment]
@t1m0n Most of the web developers use **English** has primary language, it would be really helpful if the default language changed to **English**.

**Comment by goranefbl** [comment]
and I thought this was a bug
