### ISSUE TITLE
Disabling multiple dates

### ISSUE THREAD

**Issue by humbucker81** [t1m0n/air-datepicker#167]
Could you please point me to the correct code to use to disable multiple dates (not weekdays at once,
so people can't select them from the calendar.

Many thanks !

**Comment by t1m0n** [comment]
You should check if current rendered date must be disabled in `onRenderCell` callback. Here I've created an example of how it can be done - https://jsfiddle.net/tdg9htma/

**Comment by humbucker81** [comment]
Thank you t1m0n, your example is VERY much appreciated.
Thanks again for this great plugin. Have a nice day !

**Comment by humbucker81** [comment]
Is it possible to submit disabled days for upcoming months in your example ?

**Comment by hassanejazkpr** [comment]
Can you please tell me how to disable previous dates, (select only current or future dates)?
Thanks!

**Comment by nishadtu** [comment]
HI, I want to enable only one ot two days, and need to disable all other days. Is it possible?

**Comment by janukkeb** [comment]
> HI, I want to enable only one ot two days, and need to disable all other days. Is it possible?

Hey. Did you find the solution?

**Comment by AndrewPaget** [comment]
Hi, is it possible to provide the calendar with a date range to use for blocking? For example, lets say something like...

{ start_date : 2019-08-01 , end_date : 2019-08-15 }

This could then be used to block that date range...is this possible or something similar?
