### ISSUE TITLE
Change 'datepicker' to 'airdatepicker'

### ISSUE THREAD

**Issue by dev4press** [t1m0n/air-datepicker#170]
If air-datepicker is used along side other datepicker plugins, things break, because they all use same basic CSS class and same basic function name: 'datepicker'. It would be great to rename air-datepicker so that function call is 'airdatepicker' and all CSS classes go from .datepicker to .airdatepicker.

**Comment by artknight** [comment]
+1

**Comment by mrxzm** [comment]
Conflict with jqueryUi.

**Comment by russellhoff** [comment]
+1.

When I add JqueryUI to my html, air-datepicker breaks and doesn't work.

**Comment by stevengliebe** [comment]
This would be very helpful. It's hard to use Air Datepicker in a WordPress plugin because so many other plugins use jQuery UI Datepicker which is bundled with WordPress itself. 'datepicker' is not distinct enough.

**Comment by firestar300** [comment]
+1

**Comment by fclaussen** [comment]
+1

**Comment by cristacheda** [comment]
+ 1

**Comment by diqmwl** [comment]
Please tell me what files need to be modified :(

**Comment by teom10** [comment]
I changed all declaration and uses of datepicker to airdatepicker, also a function Datepicker to AirDatePicker in datepicker.js, the i18n and css files

**Comment by d79** [comment]
+1

**Comment by harryfear** [comment]
+!

**Comment by t1m0n** [comment]
Version 2 is no longer maintained
