### ISSUE TITLE
mobile? responsiveness? 

### ISSUE THREAD

**Issue by yairEO** [t1m0n/air-datepicker#18]
nothing of that is mentioned in the README, nor the demo page.. I don't want to waste time implementing this on my website then finding out it's not working well on mobiles...would be wiser to find out such things in advance. 

Thanks!

**Comment by t1m0n** [comment]
I can't say for all mobile browsers, because I'm able to test in only on iOS, and emulators. As far as I can say it should work on all last three versions of popular mobile OS.

Will include this info in docs.

**Comment by radubartan** [comment]
Timofey - do you have any suggestions what to do when the datePicker cuts off the page?
![datePicker_cuts_off_the_page](https://user-images.githubusercontent.com/6721563/64647403-f2be3000-d3e6-11e9-9475-47056d8e4226.JPG)
