### ISSUE TITLE
onClear event?

### ISSUE THREAD

**Issue by b0gd4n** [t1m0n/air-datepicker#187]
is there a way of capturing clear event?

**Comment by t1m0n** [comment]
You can use `onSelect` event for that purpose. Just check if `date` is passed to callback, and if its not, when do your `onClear` things. Check this [fiddle](https://jsfiddle.net/3fe4pm8L/)

**Comment by b0gd4n** [comment]
that's nice - problem in my case with that is that I have a onSelect listener that will redirect the page to apply a search with the selected date - this causes a loop on load

**Comment by t1m0n** [comment]
You could add flag `redirected` and if its `true` when do not redirect user inside `onSelect` event. Pseudo code might look like this:

```javascript
var redirected = false;

var dp = $('#dp').datepicker({
  onSelect: function(fd, d) {
    if (!fd) {
      // no selected dates
    } else {
    	if (!redirected) window.location = 'search/location?date=' + fd;
      redirected = false; // Reset var, to be able to redirect user on next `onSelect` event
    }
  }
}).data('datepicker');

// If we have date in query string when set `redirected` to true
if (queryDate) {
	redirected = true;
  dp.selectDate(queryDate)
}
```

**Comment by b0gd4n** [comment]
sweet - that solved my problems. Cheers!

**Comment by uncoolplane** [comment]
I'm having the same problem.  Maybe clicking the "Clear" button can also trigger the same "OnSelect" event since you are selecting an empty date?
