### ISSUE TITLE
"datepicker is not a function" error when I try to import it in a module

### ISSUE THREAD

**Issue by id247** [t1m0n/air-datepicker#196]
I'm using webpack with babel.

And if I import plugins like this:
```
import $ from 'jquery';
import 'air-datepicker';
...
$('.date-input').datepicker({
  ...
});
```

it wont work. 

But in the same time if I use '.datepicker-here' class on inputs and remove manual initialization

`// $('.date-input').datepicker();`

it works fine. 

But I need to use datepicker's events thought...

**Comment by t1m0n** [comment]
Hi!
I suppose the problem is that jQuery is not available in global context. You should include it on your page via `<script>` tag or use [webpack provide plugin](https://webpack.js.org/plugins/provide-plugin/).

**Comment by id247** [comment]
I understood that the problem was because of lack jQuery in global context. But I thought it can be avoided somehow, like binding plugin manually with 
```$.fn.plugin = plugin``` 
or something else.

I've used provide plugin from the start, it did't help (maybe i used it wrongly).

That did help is a "expose-loader", so for now all is working ok. 

Nice plugin it is, thanks for your work )
