### ISSUE TITLE
range problem

### ISSUE THREAD

**Issue by josemfr1969** [t1m0n/air-datepicker#197]
I don'n know how to initialize this datetimepicker to a predefined range.
I need it to be something like [`17/05/2017 18:00 - 18/06/2017 10:25`] but the text is always empty till I select both dates from the datetimepicker.
Help me, please.
```
<input name="rango" id="rango" type="text" size="33" class='datepicker-here'">
                <script>
                $('#rango').datepicker({
                  language: 'es',
                  timeFormat: 'hh:ii',
                  timepicker: true,
                  multipleDatesSeparator : ' - ',
                  range: true,
                  todayButton: true                 
                });
                </script>
```

**Comment by josemfr1969** [comment]
If I add `starDate: new Date();` then datepicker language return tu russian, `timpicker`, `range `an `todayButton `are set to `false`. 
Help, please.

**Comment by josemfr1969** [comment]
I have solved it using two inputs, one for start a other for end .
Great.

**Comment by t1m0n** [comment]
You could also select dates with `selectDate` method on start. Check this fiddle https://jsfiddle.net/fzvamLkg/

**Comment by nam-co** [comment]
Hi, the jsfiddle is a good example, but what happens if the dates are in the past or future, for example, instead of 2016, 4, 25 its 2017, 4, 25, when you open the date picker, it shows the current month, is there a way to specify the opening year/month?

example: https://jsfiddle.net/maksuco/fzvamLkg/2/

**Comment by t1m0n** [comment]
@nam-co Hi! You could set viewable date by setting `date` to desirable one like this:

```javascript
dp.date = new Date(2016,3,24)
```
