### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by bbenezech** [t1m0n/air-datepicker#2]
I feel it's a shame you used jQuery for an IE10+ plugin today. (I do not include it anymore in my projects)

Is there any particular pb you encountered that jQuery helped you solve or did you use it out of habit?

For ref. http://youmightnotneedjquery.com/

Sorry if I sound rude, I'm mostly curious.

Looks awesome and well documented with a nice API.

**Comment by t1m0n** [comment]
Well you right, I could write it without using jQuery, but then I had to write all these function for add-remove class (.classList for multiple elems), event delegation, object extend, triggering custom events etc. jQ makes things simple. 

Maybe in future I'll return to this issue, but not today.

Thanks for your comment.

**Comment by bbenezech** [comment]
Fair enough! Thanks for your time.

**Comment by zoxon** [comment]
@t1m0n Maybe the time has come?

**Comment by t1m0n** [comment]
@zoxon It has definitely come, I hope there will be opportunity to remove jQuery from calendar in near time.

**Comment by zoxon** [comment]
@t1m0n That's good news.
If you need help, I have a lot of experience [rewriting from jQuery to vanilla JavaScript](https://github.com/zoxon/gulp-front/commit/2490fe90ac55a8168959a330c688274a4529fd20)

**Comment by t1m0n** [comment]
@zoxon thanks for the offer of help, but I'd like to do it myself
