### ISSUE TITLE
Интеграция в React

### ISSUE THREAD

**Issue by liketurbo** [t1m0n/air-datepicker#208]
Как интегрировать это с React?

**Comment by t1m0n** [comment]
Какая у вас именно проблема?
Можно просто подключить на страницу и проинициализировать на конкретном элементе внутри React компонента.

**Comment by vippayne** [comment]
​

2017-06-23 23:17 GMT+03:00 Timofey <notifications@github.com>:

**Comment by vippayne** [comment]
объявление внутри html не помогает

2017-06-24 2:04 GMT+03:00 Ramzan Chasygov <theliketurbo@gmail.com>:

**Comment by t1m0n** [comment]
Ответил вам на [stackoverflow](https://stackoverflow.com/questions/44731221/how-integrate-jquery-plugin-in-react/44734500#44734500)

**Comment by liketurbo** [comment]
> Ответил вам на [stackoverflow](https://stackoverflow.com/questions/44731221/how-integrate-jquery-plugin-in-react/44734500#44734500)

LGTM
