### ISSUE TITLE
Range emitting onHide method twice

### ISSUE THREAD

**Issue by jCrip** [t1m0n/air-datepicker#212]
Hi, i'm using your plugin and is awesome. The only thing is that when range is set to true the onHide method gets fired twice.
Also onSelect is fired twice, on the first select and the second.

Maybe when range is true the onHide method should only gets fired once or a onRangeSelect() methods that's get fired when both dates are selected.

Thank you

**Comment by crivotz** [comment]
animationCompleted is the key.

```(javascript)
onHide: function(dp, animationCompleted){
  if (animationCompleted){
    console.log('something');
  }
}
```
