### ISSUE TITLE
How to make two inputs of range date-piacker.

### ISSUE THREAD

**Issue by keem1201** [t1m0n/air-datepicker#22]
From the examples, the range of dates is done within one input. Here I would like to have two inputs of range date-piacker. For example; when I already selected a check-in date, it will automatically force me to select a check-out date.

Thanks
Hakeem

**Comment by t1m0n** [comment]
There is no built in possibility to do this. You'll have to do it manually. Just focus on second input after selecting date in first one, and set `minDate` to selected date. After selecting date in second input, update `maxDate` in first one.

**Example**

```html
<input type='text' id='start'>
<input type='text' id='end'>
```
```javascript
var $start = $('#start'),
    $end = $('#end');

$start.datepicker({
    onSelect: function (fd, date) {
        $end.data('datepicker')
                .update('minDate', date);

        $end.focus();
    }
})

$end.datepicker({
    onSelect: function (fd, date) {
        $start.data('datepicker')
                .update('maxDate', date)
    }
})
```

**Comment by keem1201** [comment]
Thanks

**Comment by MikeMike-ru** [comment]
Hello! Was something changed in plugin since your answer? This doesn't work for me.

`Uncaught TypeError: t.getFullYear is not a function`

This appears in console after selecting first date. Am I doing something wrong? Thank you!
