### ISSUE TITLE
Пропадает выбранная дата после обновления страницы

### ISSUE THREAD

**Issue by sergsagan** [t1m0n/air-datepicker#238]
Приветствую, использую в работе air datepicker, очень понравился в работе. Но я столкнулся с проблемой - как сделать что бы выбранная дата записывалась в поле и не исчезала при обновлении страницы, вот мой рабочий код
`$('.datepicker-here').datepicker({

        onRenderCell: function(date, cellType) {
            if (cellType == 'day') {
                var today = new Date();
                today.setHours(0, 0, 0, 0);

                if (today && date <= +today + 86400000 * 3) {
                    return {
                        disabled: true
                    }
                }
            }
        },
        minDate: new Date(),

        position: "left bottom",

        language: {
            days: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
            daysShort: ['Su','Mo','Tu','We','Th','Fr','Sa'],
            daysMin: ['Su','Mo','Tu','We','Th','Fr','Sa'],
            months: ['January','February','March','April','May','June','July','August','September','October','November','December'],
            monthsShort: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Okt','Nov','Dec'],
            today: 'Today',
            select: '',
            clear: 'clear',
            dateFormat: 'yyyy-mm-dd',
            timeFormat: '',
            firstDay: 1
        }
    });`
значение записывается в value, но в поле input на странице не отображается.

**Comment by sergsagan** [comment]
оказалось просто: value: date

**Comment by m4tsur** [comment]
> что бы выбранная дата записывалась в поле и не исчезала при обновлении страницы

Вам надо использовать `localStorage` или `sessionStorage`, рабочий пример тут:
[https://jsfiddle.net/2c7r40g8/2/](url)

**Comment by sergsagan** [comment]
ссылка не открывается

**Comment by sergsagan** [comment]
спасибо за пример, но теперь пропала возможность выбора через 3 дня от текущей даты

**Comment by m4tsur** [comment]
> ссылка не открывается

исправил ссылку

> спасибо за пример, но теперь пропала возможность выбора через 3 дня от текущей даты

[https://jsfiddle.net/2c7r40g8/3/](https://jsfiddle.net/2c7r40g8/3/)
