### ISSUE TITLE
How to add the dragging function

### ISSUE THREAD

**Issue by jiezhang917** [t1m0n/air-datepicker#24]
Hi, this is a pretty cool datepicker. My only issue is that I want to use dragging action to select date range. I spent some time studying you functions but I got no idea about where to start. Could you please give me some heads-up about where to begin? I'm pretty a green hand on developing. Would appreciate of any kinds of help.

**Comment by t1m0n** [comment]
Hi, thanks for response!
There is no dragging functionality currently, I'll think about implementing this in future releases.

**Comment by jiezhang917** [comment]
I really love this datepicker. Kind of the most perfect one I've ever found. I do hope you can add the dragging feature. I tried to modify the codes myself but I failed by breaking all click function. What I thought is making changes on the _bindEvents function like this:
 `_bindEvents: function ()  {
              this.$el.on('click', '.datepicker--cell-month .datepicker--cell-year', $.proxy(this._onClickCell, this));
            this.$el.on('mousedown mouseup', '.datepicker--cell-day', $.proxy(this."another function", this));
}`

But it will break all click action and the mousedown mouseup on day cell is not working either. Could you give me some heads-up as I need to use this feature soon.

**Comment by t1m0n** [comment]
I made a draft version, you can try it by using this gist https://gist.github.com/t1m0n/cf91a8b5a57a4486d243. I can't guarantee proper work, but you can change it to your needs.

**Comment by jiezhang917** [comment]
Thank you so much! This is a great feature, just need some more customization by myself. I have one more stupid question if you don't mind. I want to add class to current date. I created a class called numberCircle in my style.css and add it as your onRenderCell example. But it's not working, codes are like this:
`.numberCircle {
    border-radius: 50%;

    width: 36px;
    height: 36px;
    padding: 8px;

    background: #fff;
    border: 2px solid #666;
    color: #666;
    text-align: center;

    font: 32px Arial, sans-serif;
}`
`onRenderCell: function(date, cellType){
            if(cellType == "day" && date == new Date()){
              return {
                classes: 'numberCircle'
              }
            }
          },`
Do you find the problem?

**Comment by jiezhang917** [comment]
Thank you!!!
