### ISSUE TITLE
Set a range date through javascript api

### ISSUE THREAD

**Issue by Assassinbeast** [t1m0n/air-datepicker#243]
Hi, you can use the **selectDate(new Date());** method to set a date through javascript.
But can you set a date range too?

For example, i want to set a range date from **2017-4-10** to **2017-4-15** through code.

**Comment by m4tsur** [comment]
Yes, you can set array of dates:
`datepicker.selectDate([new Date('2017-4-10'), new Date('2017-4-15')]);`

**Comment by ReHa111** [comment]
Hi,
is it possilbe to set a date-range by API, without forcing an onSelect-Event?

**Comment by m4tsur** [comment]
Hello, @ReHa111.
It's not possible without modifying source code... But if u still want to do that here is example:

changes in file: `/src/js/datepicker.js`
`L447- selectDate: function (date) {`
`L477+ selectDate: function (date, triggerOnSelect = true) {`
`L535- if (opts.onSelect) {`
`L535+ if (triggerOnSelect && opts.onSelect) {`

(default) set date WITH onSelect event trigger:
`datepicker.selectDate(new Date());`

set date WITHOUT onSelect event trigger:
`datepicker.selectDate(new Date(), false);`
