### ISSUE TITLE
Default minute value

### ISSUE THREAD

**Issue by luke82** [t1m0n/air-datepicker#258]
Hello,
I set option "minutesStep" to value 30. Just I can select only 0 minute and 30 minutes. It's OK. But, when plugin is intialized, default value of minutes is actual time. For example 18 minutes, 33 minutes etc. How can I set default value of minutes on 0?
Thank you.

**Comment by t1m0n** [comment]
Hi! You could set `startDate` with desirable time. For example:

```javascript
var date = new Date();
date.setMinutes(30);

$('.el').datepicker({
    startDate: date
})

**Comment by luke82** [comment]
It works. Thank you.

**Comment by kl3sk** [comment]
Hello,

This is working but the date is set at the AirDatePicker initialisation, is there a way to use a callback (or something else) to compute the time when I want to select a date ?
