### ISSUE TITLE
Language Issues

### ISSUE THREAD

**Issue by 2rohith2** [t1m0n/air-datepicker#268]
@t1m0n I have added the following the `scripts` in my code

```
<link href="dist/css/datepicker.min.css" rel="stylesheet" type="text/css">
<script src="dist/js/datepicker.min.js"></script>
<script src="dist/js/i18n/datepicker.en.js"></script>
```

But still I see this message in my console and my language is changed to **Russian**
`datepicker.min.js:1 Can't find language "en" in Datepicker.language, will use "ru" instead`

Could you please tell me what I am missing on?

**Comment by geeseyj** [comment]
I'm having the exact same problem :/

**Comment by geeseyj** [comment]
@2rohith2  I figured out my problem, my link to datepicker.en.js wasn't correct. 😆 

I would double check that first.

**Comment by 2rohith2** [comment]
@geeseyj My link to `datepicker.en.js` is correct.
Sometimes the calendar is shown in `English`, no idea what I am missing

**Comment by 2rohith2** [comment]
This issue is due to order of jquery,
