### ISSUE TITLE
Security Issue - Minimum and maximum dates can be avoided

### ISSUE THREAD

**Issue by 2rohith2** [t1m0n/air-datepicker#269]
@t1m0n I have date with range of max and min, user can easily override the date just by typing the year in the input field.

Please find the below attached image below
![image](https://user-images.githubusercontent.com/5773985/37097523-ad807596-2241-11e8-9c46-7fc82d79c29f.png)

How I can prevent this happening?
**Suggestion** : mask all the background elements (ex: bootstrap model) behind the calendar, when user clicks on the input field calendar should show and mask/blur rest of the elements.

**Comment by Davecave** [comment]
Try adding "onkeydown="return false" to your input field. This solved the problem for me.
