### ISSUE TITLE
About the css file

### ISSUE THREAD

**Issue by jiezhang917** [t1m0n/air-datepicker#27]
Hi Timofey, I want to use my own styles for selection, focus, range-from and range-end and also. I read your documentation, which is clear for almost everything, but didn't say anything about using personal them. I'm wondering should do something like jQuery addClass() in my js file or create my own datepicker.css to replace yours? I know both will work, but considering the future maintenance, which way is better? I appreciate so much for your knowledge!

**Comment by t1m0n** [comment]
You can use option `classes` to add custom classes to datepicker and apply your styles to it.

```javascript
$('#datepicker').datepicker({
    classes: 'my-custom-datepicker'
})
```

**Comment by jiezhang917** [comment]
I know. But this can only apply classes to the whole datepicker div right? I also need to change the cell style and range selection style. Currently, I copied your datepicker.css file and made some changes and everything is working fine. Just not sure whether this is a good way to use plugin.
