### ISSUE TITLE
selectedDate not working on initialization

### ISSUE THREAD

**Issue by 01CodeLT** [t1m0n/air-datepicker#279]
I have the following code but when the page loads the date of tommorow isn't selected.

`var tommorow = new Date();
  tommorow.setDate(tommorow.getDate() + 1);
  $('#calendar').datepicker({language: 'en', minDate: new Date(), inline: true, multipleDates: true, multipleDatesSeparator: ',', dateFormat: 'd-M-yyyy', selectedDates: [tommorow] })`

Regards,
Luke Tinnion

**Comment by m4tsur** [comment]
There is no option `selectedDates`, just use `selectDate()` method after datepicker init.
Here is working example: https://jsfiddle.net/yLho5w9f/2/

**Comment by 01CodeLT** [comment]
Cheers I did end up using that function.
