### ISSUE TITLE
Issues Disabling Multiple Dates 

### ISSUE THREAD

**Issue by Kcardenas01** [t1m0n/air-datepicker#287]
Im not sure what i'm doing wrong but no matter what I try the dates won't show up disabled, and now when I tried to make an example to show it won't even pop up now in my jsfiddle :( here is  the link: https://jsfiddle.net/Kcardenas01/ok9g5r2s/2/

**Comment by m4tsur** [comment]
https://jsfiddle.net/ok9g5r2s/25/

**Comment by Kcardenas01** [comment]
Thank you soo much!
