### ISSUE TITLE
How about adding timepicker?

### ISSUE THREAD

**Issue by iambillywilly** [t1m0n/air-datepicker#3]
It would be cool if could choose the time too. How about that?

**Comment by t1m0n** [comment]
I didn't planned to add timepicker, maybe I'll do it as separate package, but don't sure about that.

**Comment by Roins** [comment]
```js
        set focused(val) {
            if (!val && this.focused) {
                var $cell = this._getCell(this.focused);

                if ($cell.length) {
                    $cell.removeClass('-focus-')
                }
            }
            this._focused = val;
            this.date = val;
        },

        get focused() {
            return this._focused;
        },

        get parsedDate() {
            return Datepicker.getParsedDate(this.date);
        },

        set date (val) {
            if (!(val instanceof Date)) return;

            this.currentDate = val;

            if (this.inited && !this.silent) {
                this.views[this.view]._render();
                this.nav._render();
                if (this.visible && this.elIsInput) {
                    this.setPosition();
                }
            }

            return val;
        },

        get date () {
            return this.currentDate
        },

        set view (val) {
            this.viewIndex = this.viewIndexes.indexOf(val);

            if (this.viewIndex < 0) {
                return;
            }

            this.prevView = this.currentView;
            this.currentView = val;

            if (this.inited) {
                if (!this.views[val]) {
                    this.views[val] = new Datepicker.Body(this, val, this.opts)
                } else {
                    this.views[val]._render();
                }

                this.views[this.prevView].hide();
                this.views[val].show();
                this.nav._render();

                if (this.opts.onChangeView) {
                    this.opts.onChangeView(val)
                }
                if (this.elIsInput && this.visible) this.setPosition();
            }

            return val
        },

        get view() {
            return this.currentView;
        },

        get cellType() {
            return this.view.substring(0, this.view.length - 1)
        },

        get minTime() {
            var min = Datepicker.getParsedDate(this.minDate);
            return new Date(min.year, min.month, min.date).getTime()
        },

        get maxTime() {
            var max = Datepicker.getParsedDate(this.maxDate);
            return new Date(max.year, max.month, max.date).getTime()
        },

        get curDecade() {
            return Datepicker.getDecade(this.date)
        }
```

hello , Please tell me how to use `get` and `set` in IE8 ~ Thank you very much
>code in datepicker.js start line 912

**Comment by Sogl** [comment]
+1

**Comment by kbradl16** [comment]
+1

**Comment by Sogl** [comment]
Also good plugin:
http://xdsoft.net/jqplugins/datetimepicker/

I change it to yours after you add this feature :wink:

**Comment by yairEO** [comment]
:+1:

**Comment by bjarnef** [comment]
+1 :+1:

**Comment by bjarnef** [comment]
@t1m0n I can see you have added a timepicker in this commit.
https://github.com/t1m0n/air-datepicker/commit/c648cba3abffd63871d6fc2491f7dad6d0dc1ca7

Do you have an example of the datepicker with the timepicker to try it out?

**Comment by m4tsu** [comment]
@bjarnef you can use [dev-branch](https://github.com/t1m0n/air-datepicker/tree/develop) to play around with timepicker.
Here's timepicker defaults:
```
timepicker: false,
dateTimeSeparator: ' ',
timeFormat: '',
minHours: 0,
maxHours: 24,
minMinutes: 0,
maxMinutes: 59,
hoursStep: 1,
minutesStep: 1,
```
![datetimepicker-demo](https://cloud.githubusercontent.com/assets/5437930/14404615/df4d8a34-fe83-11e5-922d-30765842e88e.png)

**Comment by yairEO** [comment]
@m4tsu - this design is beautiful, I love it! it would be great if both the calendar and the time picker were separate components, merged together in your build process and nicely minified, ready for consumption for the end-user.

**Comment by bjarnef** [comment]
@m4tsu okay, will check it out. I think the datepicker works great on touch too - did you try the timepicker from a touch device?

Maybe it will work better with timepicker in a separate view or click/tap on hours/minutes open a new view like this one https://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by m4tsu** [comment]
@yairEO @bjarnef don't forget **[this is development version](https://github.com/t1m0n/air-datepicker/tree/develop)** and may be changed/redisigned many times, so we can discuss it only after stable release...
@bjarnef I tried it on mobile(Android) Firefox - works great, but have some style issues.

**Comment by bjarnef** [comment]
@m4tsu yes, and better to suggest ideas now rather than when the final release is out :)

**Comment by kbradl16** [comment]
What about an option for milliseconds?

**Comment by bjarnef** [comment]
I had a look at the new timepicker, but when using a date range or multiple dates, the time only seems to affect last selected date. It should somehow be possible to adjust time from start or end date - or select which date you want to adjust time for.
For multiple dates (incl. date range) maybe it would make sense to have a checkbox "sync time for all dates", so you only have to adjust time once.

**Comment by t1m0n** [comment]
@bjarnef I'm thinking of adding a hot key for choosing which date to format. Maybe it'll be `Ctrl + Left Mouse`. It also could be used for choosing multiple dates and change time simultaneously on selected cells.

As for mobile devices, I've only checked on iOS, but i think it should work fine on Android too. Maybe some font and styles issues can occur. Sliders are just `<input type="range" />` so I don't think there'll be much problem with them.

@kbradl16 I can't think of cases where it could be useful. I thought about adding `seconds` but decided not to add them yet.

**Comment by bjarnef** [comment]
@t1m0n okay, but that wont work on a mobile/touch device :)
