### ISSUE TITLE
Can we add multiple months? 

### ISSUE THREAD

**Issue by dramen** [t1m0n/air-datepicker#30]
is it possible to make it multiple months for range? it would be good if you could set it 2 moths to view so range selection would make more sense. In jquery ui option is available via "numberOfMonths" parameter. Awesome datepicker! Thanks.

**Comment by t1m0n** [comment]
Unfortunately there is no option for that currently. There is already #8, so I'll close this one. 
Thanks for response.

**Comment by guybader** [comment]
@t1m0n Hey, is it been added
