### ISSUE TITLE
ошибка с старт дате 

### ISSUE THREAD

**Issue by muhiddingithub** [t1m0n/air-datepicker#31]
"Uncaught TypeError: this.date.getTime is not a function"
у меня появляются токово ошибка, если я добавляю старт дате на датепиккер , на документация написано что датепиккер подерживает старт дате а протика покажет набарот

**Comment by t1m0n** [comment]
В `startDate` нужно передавать объект даты `new Date()`. Скорее всего вы передаете что-то другое. Вот работающий пример (начальная дата будет равна Июню 2012 года):

```javascript
$('#dp').datepicker({
     startDate: new Date(2012, 5)
})
```

**Comment by ralex123** [comment]
А если передать new Date(2012, 5, 15). Дата 15 июня 1012 не выбирается. Почему?
