### ISSUE TITLE
Air Datepicker is messing up the page width completely!!?

### ISSUE THREAD

**Issue by ahmad-atallah** [t1m0n/air-datepicker#312]
@t1m0n I started to use this cool plugin recently, I just noticed it's messing up the page width..
The weird thing is, whenever I click on the input and the calendar opens, the width will be fixed and the scroll bar disappears!!
Please have a look on the attached screenshot below.
```

<div class="row">
   <div class="col-12">
      <input type='text' class="datepicker-here form-control w-25 pull-left" data-position="right top" data-language='en' data-min-view="months" data-view="months" data-date-format="MM yyyy" id="my-element" />
    </div>
</div>
```
![capture2](https://user-images.githubusercontent.com/6143290/46954282-d6135e00-d098-11e8-830a-fab99859cb5c.png)

Any suggestions?

**Comment by t1m0n** [comment]
Do you have any live examples of this issue?

**Comment by ahmad-atallah** [comment]
[html v3-10 -report.zip](https://github.com/t1m0n/air-datepicker/files/2490366/html.v3-10.-report.zip)

@t1m0n thank you for your reply! 
Please check the attached file, you will find one HTML file "reports-2.html"

Thanks again..

**Comment by ahmad-atallah** [comment]
[html v3-10 -report.zip](https://github.com/t1m0n/air-datepicker/files/2490833/html.v3-10.-report.zip)

@t1m0n  thank you for your reply! 
Please check the attached file, you will find one HTML file "reports-2.html"

Thanks again..

**Comment by t1m0n** [comment]
Hm, it looks like `direction: rtl;` and `left: -10000px` are cause this overflow behaviour. Instead of  applying `direction: rtl` to `body` you could assign it to all child elements like this:

```css
body > * {
  direction: rtl;
}
```
This should fix issue.

**OR**

You could swap `left` to `right` in datepicker styles:

```css
.datepicker {
  left: auto;
  right: -10000px;
}

.datepicker.active {
  right: unset;
}
```
