### ISSUE TITLE
Перенос репозитория в отдельную группу

### ISSUE THREAD

**Issue by serieznyi** [t1m0n/air-datepicker#321]
@t1m0n 
Приветствую.
Я давно знаком с вашим проектом и он мне очень нравится.
Как видите не мне одному, о чем говорят звезды и кол-во issues, и PRs. 
Видимо у вас нет достаточного количества свободного времени что бы заниматься проектом.
По крайней мере вы так сказали в https://github.com/t1m0n/air-datepicker/issues/273
А вы не думали перенести данный репозиторий в одноименную организацию и найти несколько core разработчиков вам в помощь? 
Это как минимум не позволит умереть отличному проекту и позволит ему развиваться.
Вероятно некоторые пользователи которые увели fork вашего репозитория вперед не откажутся от участия в этом мероприятии.
Что вы об этом думаете?

**Comment by tibrus** [comment]
+
