### ISSUE TITLE
set default value

### ISSUE THREAD

**Issue by zeroone2005** [t1m0n/air-datepicker#322]
if input has value 
`<input name="date" id="date" value="2018-12-01" />`

js:
`        $('#date').datepicker({
            language  : 'zh',
            dateFormat: 'yyyy-mm-dd',
            autoClose : true,
            minDate   : new Date()
        });`

datepicker can't **auto** set default value from text value

**Comment by bladeaweb** [comment]
Simple variant:
`<input name="date" id="date" value="2018-12-01" /> `
js:
```
var myDataPicker = $('#date').datepicker({ 
  language : 'en', 
  dateFormat: 'yyyy-mm-dd', 
  autoClose : true
}).data('datepicker');
if ($('#date').val() === '') {
  myDataPicker.selectDate(new Date($('#date').val()));
}
```
I think it should work as you need.
https://codepen.io/blade_didan/pen/gQeOxM

**Comment by zeroone2005** [comment]
it's only way;

**Comment by VlLight** [comment]
Could you suggest me some solution to same action for datepicker in "month mode" (view: 'months', minView: 'months')? I set date for first day of month (Nov 2018, for example) but datepicker opens window for 2019's months)

**Comment by cmnstmntmn** [comment]
@zeroone2005 is there a simple way, to init elements with their initial value - `target.value()`?

```js
var dp = $('.datepicker-here').datepicker({ 
        language : 'en', 
        dateFormat: 'yyyy-mm-dd', 
        autoClose : true
    })
    .data('datepicker')
    .selectDate($el.value())
```

i can't find no reff to the current element.
thank you

**Comment by ivan-cc** [comment]
> @zeroone2005 is there a simple way, to init elements with their initial value - `target.value()`?
> 
> ```js
> var dp = $('.datepicker-here').datepicker({ 
>         language : 'en', 
>         dateFormat: 'yyyy-mm-dd', 
>         autoClose : true
>     })
>     .data('datepicker')
>     .selectDate($el.value())
> ```
> 
> i can't find no reff to the current element.
> thank you

https://github.com/t1m0n/air-datepicker/issues/372
