### ISSUE TITLE
Single DOM element datepicker

### ISSUE THREAD

**Issue by betmakh** [t1m0n/air-datepicker#33]
How about to manipulate only one DOM element (datepicker) and rerender it on each input field, instead of creating new datepicker on each input field?

**Comment by t1m0n** [comment]
If datepicker will be rendered in single DOM element then appear/hide animation will break. For example when you focus from one input with datepicker to another. So I guess it can't be done.

**Comment by betmakh** [comment]
What about add option which is toggle animation and/or setup datepicker behavior (single dom element/multiple dom elements)?
