### ISSUE TITLE
NAN bug on Safari 

### ISSUE THREAD

**Issue by cpowerfanomena** [t1m0n/air-datepicker#338]
Great plugin! My company makes extensive use of it across their application and it works like a charm across most browsers, however we have noticed on Safari on Mac that a NAN error is generated when trying to edit an existing date. 

Screenshot: https://imgur.com/a/qmAtgrm

**Comment by vgarcia007** [comment]
Having the Same Problem.
I think it has something to do with the default date format.

**Comment by cpowerfanomena** [comment]
we switched to a datepicker that uses momentJS in the end

**Comment by vgarcia007** [comment]
I wanted to use air-datepicker because of the inline feature.
But its useless the way it is. The majority of users has Apple Phones :(
Can you give me the name of the plugin?

**Comment by cpowerfanomena** [comment]
http://www.flatpickr.com/ best of luck :)

**Comment by vgarcia007** [comment]
Thank You. This looks nice!
