### ISSUE TITLE
Ошибка Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by yumashev** [t1m0n/air-datepicker#35]
Пытаюсь подключить плагин в WordPress.
Получаю ошибку: https://monosnap.com/file/DeLrGSRFkZ0824XtLFGeqlwXqYM51h
datepicker.min.js?ver=4.4.2:1
Uncaught TypeError: $ is not a function

Обычно такие ошибки бывают в WP если jQuery плагин загружается до загрузки самого jQuery.
Но я знаю об этом и в WP есть логика последовательности. Она учтена и плагин точно подгружается после jQuery https://monosnap.com/file/qzQr3tIbytuODwLpo7VVrhF4VkOYSN

Пробовал активировать логику через ручной режим без класса в режиме noConflict https://api.jquery.com/jquery.noconflict/

        `jQuery(document).ready(function($) {           
            $('.datepicker-air').datepicker();
         });`

Бесполезно.

Может быть будут идеи что не так?

**Comment by t1m0n** [comment]
Я, к сожалению, не знаком с WordPress, не могу ничего внятного сказать. Попробуйте обновиться, я обернул весь плагин в `;(function (window, $, undefined) { ... })(window, jQuery);`, возможно это исправит проблему.

**Comment by yumashev** [comment]
Все заработало! Большое спасибо! :)
