### ISSUE TITLE
readonly, placeholder issues

### ISSUE THREAD

**Issue by sergei0** [t1m0n/air-datepicker#36]
Timofey, 
1. Air-datapicker shows on "readonly" inputs.
<input type="text" class="datepicker-here form-control" name="DOI" readonly>
2. "placeholder" produces strange behavior (requires multiple clicks to change empty or the same date).
<input type="text" class="datepicker-here form-control" name="DOI" placeholder="mm/dd/yyyy">
3. Request: TODAY button on Click - populate current date (maybe after selecting it on datepicker as now) and close datepicker (if autoClose)
4. Request: auto (relative) datepicker position 

PS. IE 11

**Comment by t1m0n** [comment]
What do you mean by 1 ? It should show on 'readonly' inputs.

**Comment by sergei0** [comment]
And change ‘readonly’ value?

**Comment by t1m0n** [comment]
Why not? `readonly` prevents from user's input only. You can change value through JavaScript. What are you trying to achieve?

**Comment by sergei0** [comment]
> readonly prevents from user's input only.

But air-datepicker changes readonly values –> user can ckick on air-datepicker and change the value that supposed to be constant.

 Sergei Alkhovik
 Programmer / Analyst

 EbixExchange
 Direct +1 404 604 2757 ext. 9940 | Fax +1 678 281 2019 | Cell +1 678 447 3624
 Email Alkhovik.Siarhei@ebix.com<mailto:Alkhovik.Siarhei@ebix.com> | Web www.ebix.com<http://www.ebix.com/>
[ebix_exchange multi color]

**Comment by t1m0n** [comment]
Usually `readonly` used in cases where you want date to be always valid. User can't change value manually, only through plugin. If you want to keep input value constant, when don't apply plugin to it, or make it `disabled`.

**Comment by sergei0** [comment]
>https://www.w3.org/TR/html401/interact/forms.html#read-only:
When set, the readonly attribute has the following effects on an element:
Read-only elements receive focus but **cannot be modified** by the user.

You plugin ignores this and allows to user change the value.

Yes, for now I (must) use disabled status.

**Comment by t1m0n** [comment]
No, it not ignores this rule: user can't change value by keyboard or by pasting new value. But it can be modified by program, it can receive focus, that's what makes these inputs very useful for developer.

I think its kinda philosophical question: can program change `readonly` values or not. I think it can, so i won't change this behavior.

It's up to you to deiced how to handle this kind of situations.

**Comment by sergei0** [comment]
>I think its kinda philosophical question: can program change readonly values or not. 
I'm not talking about program. Now user by clicking on readonly input field can popup datepicker and change the readonly value. And I think this is incorrect. 
But it's your plugin - you are the boss.

**Comment by jonnyserra** [comment]
I'm also having the same issue namely with placeholders on IE-11, if i add a placeholder to the input field on which i'm calling the datepicker, suddently it requires double clicks to select any of the datepicker cells, this problem does not occur on Chrome and i need the datepicker working on IE 11 at least, any ideas as to how we can do this? This ruins UX on IE :\

**Comment by t1m0n** [comment]
@jonnyserra it already fixed in [`dev`](https://github.com/t1m0n/air-datepicker/tree/develop), you can try to use it until next version is released.

**Comment by mzaini30** [comment]
Try add: 

```css
<style>
    .datepicker--days.datepicker--body.active {
        pointer-events: none;
    }
</style>
```

It's worked for me... @t1m0n
