### ISSUE TITLE
"dateFormat: 'yyyy-mm-yy'" parameter doesn't work

### ISSUE THREAD

**Issue by Dzhuneyt** [t1m0n/air-datepicker#368]
Whenever I use the following code:

```
            $(this).datepicker({
                dateFormat: 'yyyy-mm-yy', // problematic parameter
                language: 'en',
                position: 'right top',
                onSelect: function () {
                    // recalcReservationSummary();
                }
            })
```

I get the following effect (video): https://imgur.com/a/cX87veC

In other words, no matter which date I select from the picker, it always fills the field with some arbitrary value "2019-07-19". Note that this is not even today's date. The date as of reproducing the bug on my computer is July 4th, 2019.

If I remove the `dateFormat` parameter - it starts setting the selected date correctly, but I lose the ability to format the date in that format. It starts formatting it as d/m/Y which is not understandable by my system (APIs).

**Comment by bladeaweb** [comment]
Try to look to your code more atencion, and you will see that it work properly how you have written it. 
'yyyy-mm-yy' = year 4 digits, month 2 digits with zero, year 2 digits.
If you need days, you need write 'dd'.

**Comment by Dzhuneyt** [comment]
Oh man, I must be blind. Thanks! :)
