### ISSUE TITLE
Question about contribute relevance

### ISSUE THREAD

**Issue by nsyng** [t1m0n/air-datepicker#430]
@t1m0n, добрый день

Вопрос что именно будет происходить с календарём.
Сейчас вижу, что в работе версия 3.0.0.

Активно использую этот элемент, хотел бы понимать будут ли какие-то обновления и как при случае можно будет помочь в его развитии.
Лучший календарь подобного рода, который я только смог найти!

Не совсем актуальный вопрос для issue, но не нашёл ваших контактов.

**Comment by t1m0n** [comment]
@nsyng Спасибо за отзыв!
Сейчас в планах наконец-то доделать 3 версию и документацию к ней - основной целью ставил убрать из зависимостей jQuery. К текущей версии планирую слить несколько пул реквестов, и прекратить поддержку 2 версии, как она есть.

**Comment by t1m0n** [comment]
Вышла [новая версия](https://air-datepicker.com) 😄
