### ISSUE TITLE
Immediately apply changes with API Update method

### ISSUE THREAD

**Issue by User12987** [t1m0n/air-datepicker#439]
### "Update API" меняет свойства календаря, но не применяет их сразу в doom в версии 3.0.

1. Создаю календарь
2. Меняем свойство через [update api](https://air-datepicker.com/ru/methods#)
3. Ожидаю увидеть изменение, но вижу изначальную конфигурацию

Если вручную сменить месяц на следующий и вернуть прежний, то изменения проявятся.
Наверняка делаю что-то не верно и есть способ применить изменения сразу автоматически с "update API". 
Пожалуйста, укажите куда копать.

P.S. Спасибо Вам за Ваш труд! Всё работает шикарно!
Webpack 5+ с кучей преобразований, испанская локаль, много ручных изменений календаря.

HTML:
```html
<div id="dp"></div>
```

JS:
```javascript
// initialization
import AirDatepicker from 'air-datepicker'
import 'air-datepicker/air-datepicker.css'

// toady & tomorrow constants
const today = new Date() 
const tomorrow = new Date(today) 
tomorrow.setDate(tomorrow.getDate() + 1)

console.log('today', today) // 04...
console.log('tomorrow', tomorrow) // 05...

// creating datepicker
const dp = new AirDatepicker('#dp', {
	minDate: today // 04...
})

// updating datepicker
dp.update({
	minDate: tomorrow // 05...
})

// expecting to see minDate == tomorrow (05...), but see today (04...)
```

![Снимок экрана 2021-10-04 в 13 52 55](https://user-images.githubusercontent.com/44153099/135808484-9c610d8c-3434-45a5-8745-6ef97067004f.png)

UPD:
Оказывается, некоторые изменения применяются сразу. Например:
```javascript
dp.update({
	selectedDates: [tomorrow] // applies and redraws immediately
})
```

Не даётся сразу применить следующие методы:
- onRenderCell
- minDate

**Comment by t1m0n** [comment]
Добрый день, спасибо за положительный отзыв! 
Да, похоже на ошибку, постараюсь исправить на этой неделе
