### ISSUE TITLE
Вывод второго блока выбора месяца

### ISSUE THREAD

**Issue by skazhikadyadya** [t1m0n/air-datepicker#44]
Добрый день, спасибо за очень милый DatePicker. Возможно ли сделать так, чтобы можно было выбирать между одной датой и диапазоном дат? То есть, например, добавить checkbox "Показать диапазон дат", открывающий ещё один выбор месяца?

**Comment by t1m0n** [comment]
Привет, спасибо за отзыв! 
К сожалению пока такой возможности нет, возможно появится в будущих версиях. #8
