### ISSUE TITLE
cellType onRenderCell

### ISSUE THREAD

**Issue by User12987** [t1m0n/air-datepicker#444]
Здравствуйте! 
Вероятно, нашел баг или что-то делаю не так: 
Метод onRenderCell не передаёт cellType. 

```html
<div id="dp"></div>
```

```js
new AirDatepicker('#dp', {
    onRenderCell({ cellType }) {
        console.log(cellType)    // undefined
    }
})
```
<img width="454" alt="Снимок экрана 2021-10-22 в 22 47 31" src="https://user-images.githubusercontent.com/44153099/138485060-e4d0bc0e-d469-4900-92db-794601d08fc0.png">

При этом, date и datepicker передаются успешно. 

UPD:
Поскольку мы успешно получаем экземпляр календаря, я попробовал узнавать CellType по текущему виду (datepicker.currentView). Это успешно сработало. 

```js
new AirDatepicker('#dp', {
    onRenderCell({ datepicker }) {
        console.log(datepicker.currentView)    // days, month, e.t.c.
    }
})
```

**Comment by Sammyskills** [comment]
Привет,

Я вижу, что вы внесли исправление, но по причине, которую я не могу объяснить, я все еще сталкиваюсь с той же проблемой. Я использую последнюю версию 3.0.1, но все та же.
Объект типа ячейки возвращает значение undefined, а форматированная дата в функции onSelect также возвращает значение undefined. Каково решение?
![image](https://user-images.githubusercontent.com/8720569/141508869-6e275928-8479-4495-aa6e-0a52c031be70.png)
![image](https://user-images.githubusercontent.com/8720569/141509223-fbbc5efa-1fe6-4018-b202-76f6896deeac.png)

**Comment by User12987** [comment]
Hello @Sammyskills! Update 3.0.1 was before identified issue.

As author said, we can use field `type` (not `cellType`). It should look like this as I understood:

```js
new AirDatepicker('#dp', {
    onRenderCell({ type }) {    // using 'type', not 'cellType'
        console.log(type)    // now we have the same as 'cellType' 
         // you can also try 'Type' (first letter may be in upper register, I'm not sure).
    }
})
```

Also, you can try to use `datepicker.currentView` - it returns 'days', ', month',  e.t.c. For example:

```js
new AirDatepicker('#dp', {
    onRenderCell({ datepicker }) {
        console.log(datepicker.currentView)    // days, month, e.t.c.
        if (datepicker.currentView == 'days') {
         // ...do something
       }
    }
})
```

**Comment by Sammyskills** [comment]
Thanks @User12987.

I already applied your initial suggestion `datepicker.currentView` and used it to achieve what I wanted. I was only wondering if it had been fixed, or maybe I was doing something wrong.

**Comment by t1m0n** [comment]
@Sammyskills hello,I made a mistake in the name of the field. Currently it fixed in another branch and will be released soon. Currently you can access `type`  field like so:

```javascript
new AirDatepicker('#dp', {
    onRenderCell(cell) {  
       console.log(cell.type)
    }
})
```
