### ISSUE TITLE
Вопрос по методу onHide

### ISSUE THREAD

**Issue by mivalb321** [t1m0n/air-datepicker#449]
Добрый день. В новой версии метод onHide больше не получает экземпляр календаря как раньше? А как тогда можно получить введенные данные для дальнейшей обработки вначале или по завершении анимации?

**Comment by t1m0n** [comment]
Добрый день. Да и вправду, не помню почему я решил так сделать 😕. Вы можете обращаться к календарю по заранее сохраненной ссылке на него:

```javascript
let dp = new AirDatepicker('#el', {
    onShow() {
        console.log(dp.selectedDates);
    },
    onHide() {
        console.log(dp.selectedDates);
    }
})
```

**Comment by mivalb321** [comment]
> Добрый день. Да и вправду, не помню почему я решил так сделать 😕. Вы можете обращаться к календарю по заранее сохраненной ссылке на него:
> 
> ```js
> let dp = new AirDatepicker('#el', {
>     onShow() {
>         console.log(dp.selectedDates);
>     },
>     onHide() {
>         console.log(dp.selectedDates);
>     }
> })
> ```

Хорошо, спасибо. Выкрутился немного по-другому. Пришлось брать экземпляр календаря из метода onSelect, а из onHide - isFinished и объединять их во внешних функциях.
