### ISSUE TITLE
selectRange method is missing

### ISSUE THREAD

**Issue by lisa1994** [t1m0n/air-datepicker#45]
I really love this datepicker and it is working perfectly. I am using the selectDate method, which is great, but I miss a selectRange method. This would really help me getting my project just fine.

**Comment by t1m0n** [comment]
Thanks for response! Actually you can use `selectDate`  when `range: true`, just call it twice with required dates, e.g.: 

```html
<input type='text' id='dp' />
```
```javascript
var dp = $('#dp').datepicker({range: true});

dp.selectDate(new Date(2016, 3, 18));
dp.selectDate(new Date(2016, 3, 22));
```
But now you should select dates in ascending order, if not, when it will incorrectly rendered, will try to fix this in future.

Maybe I'll add possibility to pass an array of dates to `selectDate()`.

**Comment by lisa1994** [comment]
Wow this is perfect thank you, exactly what I needed!

**Comment by beyasca** [comment]
Hi 
There is an error function. The month is growing self 1 month

```
    dp.selectDate([
        new Date(2016, 6, 10),
        new Date(2016, 6, 20)
    ]);
```

result: Selected 10.**07**.2016 an 10.**07**.2016

Please help me

**Comment by t1m0n** [comment]
@beyasca there is no error. Month is zero based, so 0 is January and 11 is December. Read more about it here - https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date

In your example `new Date(2016, 6, 10)` is July 10 2016

**Comment by beyasca** [comment]
Thank you. January is 1, Although it would be easy
