### ISSUE TITLE
Не вызывается onChange у input при закрытии календаря.

### ISSUE THREAD

**Issue by touol** [t1m0n/air-datepicker#450]
Добрый день! Понравился ваш компонент. Попытался прикрутить его в свой компонент, но появилась проблема: Не вызывается onChange у input при закрытии календаря. А у меня при onChange поля даты запускается фильтрация таблицы. 
Это основная проблема.
Есть еще один момент, которые мне нужны. Это одним вызовом прикрутить календарь ко всем элементам с классом .get-date. В том числе к элементам которых еще нет, но будут подгружены по ajax.
Я бы наверно сделал форк вашего календаря и сам прикрутил нужное, но сейчас мне даже не понятно как из исходников собрать дистрибутив :-(.

**Comment by t1m0n** [comment]
Добрый день! `onChange` не вызывается при закрытии календаря, попробуйте завязаться на методы `onHide` или `onSelect` в самом календаре.

По второму вопросу - вам самому нужно циклом пройтись по всем элементам с нужным классом и проинициализировать календарь на  каждом элементе. С подгрузкой тоже самое, это логика на вашей стороне.
