### ISSUE TITLE
Picking single date when range is true

### ISSUE THREAD

**Issue by jesperbjoernandersen** [t1m0n/air-datepicker#452]
Is it possible to have the datepicker just select a single date when you click it twice, while range is set to true?
I'm using it to pull out statistics for a set date range, and I was to be able to pick 1 date as well as a range of multiple.

**Comment by t1m0n** [comment]
Hello, yes, you could set `toggleSelected: false` , this will allow you to select same day twice in range mode.

**Comment by jesperbjoernandersen** [comment]
You saved my life! Thank you!
