### ISSUE TITLE
Как отключить выбор дат, но оставить просмотр выбранных?

### ISSUE THREAD

**Issue by hramenko** [t1m0n/air-datepicker#454]
При инициализации задаю массив дат selectedDates и toggleSelected: false,
Снять при этом выделение пользователь не сможет, но остаётся возможность выбрать что-то ещё.
Если в onRenderCell возвратить disabled: false на ячейку дня, то они все становятся серыми, а класс выбранных снимается,
В итоге возможности оставить только просмотр выбранных дат не нашёл.

Временно можно установить стиль pointer-events: none для ячеек, но это трубает интерактивность переходов,
т.е. при клике на первое число следующего месяца в календаре пользователь уже не попадёт на тот месяц, также, как и обратно, только стрелками выбора месяца.  И ещё, при таком переходе эта дата отмечается выбранной, что логично, но в моём случае этого не надо.

**Comment by hramenko** [comment]
решение простое
```
const eventDates = ['12.08.2021','2021-07-25', '2021-07-20'];				
const eventCalendar = new AirDatepicker('#event-calendar',{					
   multipleDates: tourDates.length,
   toggleSelected: false,
   selectedDates: tourDates});
```
пожалуй не хватает отображения нескольких месяцев одним календарём

**Comment by t1m0n** [comment]
Рад, что вы нашли решение
