### ISSUE TITLE
Как перепрыгивать месяцы? исключить из перелистывания отдельные?

### ISSUE THREAD

**Issue by hramenko** [t1m0n/air-datepicker#455]
Если в массиве выбранных дат нет какого-то месяца,
то при перелистывании месяца хочется переходить на следующий или предыдущий имеющийся в массиве дат.
Пробовал через onChangeViewDate, но в событии мы имеем только представление о дате, куда уже перелистнули, а не куда собираемся перейти.
Здесь, чтобы выполнить скип вызовом next,() или prev() надо иметь информацию о том, какой год и месяц был до вызова события, типа oldMonth, oldYear, и было бы неплохо чтобы дальше можно было вернуть нужный месяц или год для перехода.

Какие могут быть решения?

**Comment by t1m0n** [comment]
Вы можете сами сохранять предыдущую дату во внешней переменной. Вот небольшой пример - здесь не даем выбирать январь и март:

https://codesandbox.io/s/suspicious-frog-s4jdu?file=/src/index.js

```javascript
let notAllowedMoths = [0, 2];
let startDate = new Date('2021-12-01');
let prevDate = startDate;

let options = {
  startDate,
  onChangeViewDate({year, month}){

    let prevTime = prevDate.getTime();
    let changeDate = new Date(year, month, 1);

    prevDate = changeDate;

    if (notAllowedMoths.includes(month)) {
      if (prevTime < changeDate.getTime()) {
        dp.next();
      } else {
        dp.prev();
      }
    }
  }
};

let dp = new AirDatepicker("#dp", options);
```
Но только еще нужно придумать как обрабатывать переход года к виду месяца, думаю тут тоже можно найти решение.

**Comment by hramenko** [comment]
Примерно так и делал, но получилось несколько жирнее, было бы здорово из этого события возвращать календарю год и месяц, ну и иметь год/месяц предыдущие сразу в событии, без объявления переменных выше, возможно было бы лаконичнее.
Календарь хороший, но в продакшене я его ещё не применял. Хочется иметь возможность отображения нескольких месяцев, как у лайтпикера, и кастомные всплывающие тултипы на ячейках дней, есть такое в планах?
