### ISSUE TITLE
Timepicker trigger hide/show on first slider movement

### ISSUE THREAD

**Issue by g-stefan** [t1m0n/air-datepicker#456]
**AirDatepicker v3.0.1**
_Browser: Chrome Version 96.0.4664.45 (Official Build) (64-bit)_
Initialization code:
```
new AirDatepicker("#datepicker", {
    autoClose: true,
    timepicker: true
});
```
**Problem:**
After the input get focus and AirDatepicker show, if a click is given and drag is performed on slider bar for hour or minute change,
the picker will perform a hide/show animation, the focus on slider is active. This will happen only once, on next click and drag everything is ok.
**Current solution:**
Set  autoClose: false if timepicker: true and close picker by other means (user change focus)

**Css problem:**
On .air-datepicker.-only-timepicker- > .air-datepicker--time  => border-top should be set to 0

**Comment by t1m0n** [comment]
Hi, thanks for the bug report, I will check it.
