### ISSUE TITLE
Метод selectDate. Аргумент silent не срабатывает.

### ISSUE THREAD

**Issue by sergeyvetrov** [t1m0n/air-datepicker#457]
Опишите пожалуйста пример использования

**Comment by t1m0n** [comment]
К примеру, если у вас такая конфигурация:
```js
let dp = new AirDatepicker('#dp', {
    onSelect(){
        console.log('select callback')
    }
})
```

и где-то дальше вы вызываете метод `dp.selectDate(new Date(), {silent: true})`, то функция `onSelect`  из начальной конфигурации не будет вызвана
