### ISSUE TITLE
инициализация 

### ISSUE THREAD

**Issue by YurMi** [t1m0n/air-datepicker#458]
может поможете?(
уже не знаю как. Написал всё как в инструкции, не работает
![Screenshot 2021-12-07 at 16 33 40](https://user-images.githubusercontent.com/70280514/145048624-829ec239-2b1a-4450-b66e-7aa6434d7eec.png)...выбивает ошибку:
Uncaught SyntaxError: Cannot use import statement outside a module

**Comment by t1m0n** [comment]
Если вы подключаете файл напряму на страницу, то импортировать ничего не нужно, можно просто инициализировать его без первой строчки в `main.js`
