### ISSUE TITLE
Range on iPhone is not working 

### ISSUE THREAD

**Issue by lisa1994** [t1m0n/air-datepicker#46]
I am using your datepicker in an app, which is also running on iOS. My problem is, that my picker (range=true) is not using range all the time. Sometimes you can select single dates, which results in enddate 14.03. and startdate 02.03. which is not possible in reality. Is there a possibility to handle this behaviour?

**Comment by t1m0n** [comment]
I'm probably understand what do you mean, but can't reproduce it, could you provide live example or something?

**Comment by lisa1994** [comment]
![datepicker](https://cloud.githubusercontent.com/assets/12426424/15144516/2814766c-16b0-11e6-990e-471c4f735de6.PNG)

This is how the problem looks. Range is defined and perfectly working, when the selected enddate is after the selected startdate. But as soon as I am shifting and positioning the enddate before the startdate, the case on my picture happens. I hope you can help me :)

**Comment by lisa1994** [comment]
This works perfectly thank you very much!

**Comment by yurvice** [comment]
Доброго дня Тимофей. Вы очень здорово постарались над календарем. Пока лучше я не нашел. Но у меня таже проблемка, в ios не работает выбор дапазона дат. Календарь подключил 2.2.3. Сайт пока лежит тут http://qube.devruso.ru/html/. Буду очень рад совету, так как это последнее что оказалось не ожиданным.

**Comment by t1m0n** [comment]
@yurvice Привет! А как это проявляется? Потому что я проверяю на ios 11, все работает.
