### ISSUE TITLE
[sass] Error: Parentheses aren't allowed in plain CSS.

### ISSUE THREAD

**Issue by aleks-and** [t1m0n/air-datepicker#461]
Здравствуйте.

![image](https://user-images.githubusercontent.com/44006743/146829886-41d27b85-a503-4d93-bee9-d7e9c05c6649.png)

"air-datepicker": "^3.1.0",
"sass": "^1.38.2"

Очень похоже на https://stackoverflow.com/questions/66083546/sasserror-parentheses-arent-allowed-in-plain-css

**Comment by t1m0n** [comment]
Добры день, да, похоже что так, разберусь, спасибо.
