### ISSUE TITLE
Datepicker switching to default language (RU)

### ISSUE THREAD

**Issue by edu27** [t1m0n/air-datepicker#463]
Hi,

While quickly navigating months, widget reload to default state changing language and date.

https://drive.google.com/file/d/1dZKXXo15Jn3AoV_JzhonC8fIPM3XhQKK/view?usp=sharing

**Comment by t1m0n** [comment]
Hi, couldn't reproduce this behaviour. Do you call `update` method or anything?

**Comment by edu27** [comment]
Hi @t1m0n, I fixed it. I was instancing the datepicker twice.

Thanks for your help.
