### ISSUE TITLE
Не срабатывает autoClose при  range: true

### ISSUE THREAD

**Issue by seva100seva100** [t1m0n/air-datepicker#466]
Приветствую. Версия air-datepicker 3.1.0
Если календарь находится в режиме отображения диапазона дат (range: true), то даже при выставленном свойстве "autoClose: true" календарь автоматически не закрывается. 

> new AirDatepicker('#dateselect', {
>         range: true,
>         autoClose: true,
> }

**Comment by t1m0n** [comment]
Привет! Спасибо за баг репорт, гляну
