### ISSUE TITLE
При range: true переменная formattedDate в событии onSelect не содержит диапазон дат, а содержит первую дату

### ISSUE THREAD

**Issue by seva100seva100** [t1m0n/air-datepicker#467]
Приветствую. 
(air-datepicker version: 3.1.0)

> new AirDatepicker('#dateselect', {
>         range: true,
>         onSelect ({date,formattedDate}) {
>             console.log (formattedDate);
> }}
> 

В консоли два раза отображается первая дата диапазона.
Что я делаю не так? Спасибо.

**Comment by t1m0n** [comment]
Привет! Да, бага, буду смотреть, спасибо.

**Comment by zaandr** [comment]
Так же столкнулся с этой проблемой. Быстрый фикс "multipleDates": true, так как там стоит проверка
```
onSelect({
    date: multipleDates ? dates : dates[0],
    formattedDate: multipleDates ? formattedDates : formattedDates[0],
    datepicker
});
```
@t1m0n Это так и задумано? Или это баг?

**Comment by t1m0n** [comment]
@zaandr это баг конечно)
