### ISSUE TITLE
Wrong timepicker value on init with inline option

### ISSUE THREAD

**Issue by Xenosiv** [t1m0n/air-datepicker#468]
I create Airpicker with inline: true

let start_date = new Date(1640178000 * 1000)

Then i do .selectDate(start_date ). It shows correct date, but wrong time (current system time, not start_date time)

But without inline option it works as must

**Comment by t1m0n** [comment]
Hello! You should pass `{updateTime: true}` as second argument to update time - 

```javascript
datepicker.selectDate(new Date(1640178000 * 1000), {updateTime: true})
```
