### ISSUE TITLE
Заблокировать ячейку по конкретной дате

### ISSUE THREAD

**Issue by SWAT727** [t1m0n/air-datepicker#473]
Добрый день. Пытаюсь прикрутить календарь к букингу.
Из примеров по работе со свойством  `onRenderCell` выходит, что оно меняет сразу все указанные номера ячеек во всех месяцах. Или я не правильно понял документацию..

А как заблокировать конкретно ячейку по дате? Например что бы не каждое 20 число, а только 20.01.2022?

**Comment by t1m0n** [comment]
Добрый день! В документации есть пример, показывающий как изменить содержимое каких-то конкретных ячеек - https://air-datepicker.com/ru/examples раздел "Содержимое ячеек". 

Вы должны каждый раз проверять, подходит ли текущая ячейка под ваше условие, если да, то возвращайте объект с `{disabled: true`}
