### ISSUE TITLE
Make work with <select>

### ISSUE THREAD

**Issue by noyearzero** [t1m0n/air-datepicker#474]
What I'd like to do is have one element that handles both the user display (localized) and the value sent to the server (unix timestamp, for example).  Since select boxes are typically used for this exact purpose, it seems logical to use them here.  I know I'd have to style it to look like a normal input, but that's fairly easy these days.  

I was trying to initialize air datepicker on a select box, but when showing it, there would be a javascript error.  So at least if that could be fixed, I could progress.  But if air datepicker had a deeper integration with select boxes, I think that would solve a lot of problems as working with multiple elements can be cumbersome.  

What I was going to try and do is:

- Disable opening of drop down on focus/click and instead open the picker
- Create a single option in the select box where the value is dateFormat and timeFormat and the visible text is the altFieldDateFormat (or maybe switch those).

I'm curious how feasible this would be.

**Comment by t1m0n** [comment]
Hello, I don't think it's a good idea to mix `<select>` and calendar. They have different purposes. From your words it seems to me that you can try to use dropdown menu with customized calendar or something like this.
