### ISSUE TITLE
Тихий режим для метода clear

### ISSUE THREAD

**Issue by aleks-and** [t1m0n/air-datepicker#477]
Добрый день.

У метода selectDate есть тихий режим. Прошу добавить такой же режим в метод clear (как вариант, и в unselectDate). Использую [AIR DATEPICKER] v.3 как основу своего дропдавн компонента, обработчик события onSelect оставил на обработку взаимодействия пользователя с календарем напрямую, все, что делаю с календарем через api своего компонента хотелось бы делать в silent режиме.

**Comment by t1m0n** [comment]
Добрый день. 
Спасибо за предложение, думаю да, нужно добавить такую возможность.
