### ISSUE TITLE
toggleSelected = true + range = true

### ISSUE THREAD

**Issue by aleks-and** [t1m0n/air-datepicker#478]
Добрый день.

Указанная комбинация опций приводит к тому, что становится невозможным выбрать одну дату (вообще, можно, перетаскиванием, но это как доп. опция) - при нажатии на день и повторному нажатию на него для завершения выбора диапазона - выбор снимается.

Как вариант. Чтобы выбрать диапазон - выбираем одну дату, вторую дату. Чтобы снять выделение  - нажимаем на выбранную дату. Но если range = true, выбрана лишь одна дата, то при повторном клине по ней - выбирать эту дату (т.е. завершаем выбор диапазона, один день). При повторном клике по выбранному диапазону в один день - снимаем выделение.

**Comment by t1m0n** [comment]
Добрый день! Да так и есть, пока кажется, что это неплохой компромисс, поэтому это поведение менять не планирую.
