### ISSUE TITLE
Not able to format selectedDates

### ISSUE THREAD

**Issue by soru95** [t1m0n/air-datepicker#487]
@t1m0n 

I have assigned a date in 'selectedDates' option to make it a pre-selected date in the input. The format I am passing to the date picker is 'E, MMM d, yyyy'.

So I am expecting that the pre-selected date should be formatted with the above date format, but the format gets applied to it when the date picker is opened i.e. when the date picker is opened, the format of the date in the text input changes to the desired format given above. When first rendered, it always shows the selectedDates in the 'MM/dd/yyyy' format.

After referring to the documentation, which says, to format selectedDates we can use dateFormat as a function where we will be manually formatting it. However, in my case, this function is never called.

The next thing I tried is when assigning the date to the selectedDates prop, there only formatted the date to the desired format.

E.g.: 

selectedDates={[format(startDate, 'E, MMM d, yyyy')]}    // format is function from date-fns library

However no effect of this change.

Surprisingly, it was giving me the date in the desired format ('E, MMM d, yyyy') when I formatted the selectedDates with the below format, I am totally blank at this point, how it's working.

 selectedDates={[format(startDate, 'dd-MM-yyyy')]}

Please help me here. Is it a defect or I am doing something wrong.

**Comment by t1m0n** [comment]
@soru95 Hello, could you please provide a live example of described behaviour? I've tried to reproduce what you are trying to achieve, and it worked fine for me - https://codesandbox.io/s/clever-mahavira-ffegd2?file=/src/index.js

**Comment by soru95** [comment]
Hey, I think I found the issue... I carefully looked into my date picker wrapper React component and found that I missed to pass dateFormat prop as config param while instantiating the date picker. I think it has solved the issue. Could you please confirm if anything else I have done wrong... Thanks in advance.

**Comment by t1m0n** [comment]
@soru95 Hi, I'm glad that you have figured it out! 
But the link you've send to me doesn't contain any example of datepicker code (maybe you already changed code there). 
If you dont' have any issues then I'm closing this ticket.
