### ISSUE TITLE
Design broken in Firefox 

### ISSUE THREAD

**Issue by lekhnath** [t1m0n/air-datepicker#489]
The design doesn't look good in Firefox web browser when timepicker is enabled  (ie `{timepicker: true}`). 

* Firefox Version : v99.0.1
* Air Datepicker version: v3.1.0

SS attached from [examples](https://air-datepicker.com/examples).

![image](https://user-images.githubusercontent.com/4231691/163659705-765fd983-0d5d-42af-a5cd-aa1b4de4ba9b.png)

**Comment by t1m0n** [comment]
@lekhnath thanks for the bug report, as a temporary solution you could apply `width: 100%` to `.air-datepicker-time--row input[type='range']`
