### ISSUE TITLE
Localization not available

### ISSUE THREAD

**Issue by stefankp** [t1m0n/air-datepicker#49]
Great Datepicker!

I installed it through Rails Assets and everything works fine, except it cannot find any localizations and therefore the calendar is in Russian.

```
Can't find language "en" in Datepicker.language, will use "ru" instead
```

Did I miss something?

**Comment by t1m0n** [comment]
Thanks for response!
You need to include localization on page, they are in `dist/js/i18n` directory.

```javascript

<script src="../dist/js/datepicker.js"></script>
<script src="../dist/js/i18n/datepicker.de.js"></script>

<input type='text' class='datepicker-here'  data-language='de'/>
```
