### ISSUE TITLE
Применение календаря более чем к одному input одновременно

### ISSUE THREAD

**Issue by larinmisha** [t1m0n/air-datepicker#494]
Столкнулся с проблемой которую не могу решить.
У меня конструктор полей в форме, я могут быть любую комбинацию полей в форме и календарь может быть больше чем 1 (хоть 10) в версии  2.2.3 я спокойно прописывал class для всех input и календарь применялся ко всем полям input данного class. 
`$('.js-datepicker').datepicker({ ... });`

В версии 3.2.0 была переработана логика вызова календаря и он применяется только к первому input 
`new AirDatepicker('.js-datepicker', { ... });`

Вопрос, как в версии 2.2.3 календаря применить его ко всем input одновременно?

**Comment by larinmisha** [comment]
Нашел вот такое решение:
```
$.each($('.js-datepicker'), function( index, value ) {
    new AirDatepicker(this, { ... });
});
```
Но столкнулся еще с одной проблемой, в обработчике onSelect, не могу получить экземпляр нужного input для получения data параметра который там хранится с момента создания input 
```
onSelect: function(date) {
     console.log($(this).data('old'));
}
```
Вопрос: чем можно заменить $(this) для получения параметра?

**Comment by t1m0n** [comment]
@larinmisha Все верно, без jQuery на множестве элементов нужно инициализировать через цикл. В цикле вы можете сохранить ссылку на нужный вам элемент и работать с ним внутри onSelect. Можно это реализовать через замыкание. 

Есть еще один способ добраться до элемента, это через свойство экземпляра календаря.

```javascript
onSelect: function({datepicker}) {
     console.log(datepicker.$el);
}
```
Это свойство не задокументировано, возможно оно изменится в будущем (скорее всего нет, но мало ли), но пока так.
