### ISSUE TITLE
 current date focus

### ISSUE THREAD

**Issue by yangyeongwon** [t1m0n/air-datepicker#495]
version : 3 

issue : Is there an option to focus on the current date when the datepicker is opened?

Expected results : 
Datepicker closed view date is August 2022.
When you reopen the date picker it should focus on June 30, 2022.

**Comment by t1m0n** [comment]
If you want just to set different view date, you could use `startDate` option. If you also want to highlight specific date you could use `setFoucsDate` method - 

```javascript
const dp = new AirDatepicker('el', {
  onShow(){
    const date = '2022-06-30';
      dp.setFocusDate(date);
      dp.setViewDate(date);
  }
})
```
