### ISSUE TITLE
Ошибка при валидации

### ISSUE THREAD

**Issue by gora2109** [t1m0n/air-datepicker#499]
Доброго времени суток. Мне нравится Ваш плагин v3 и использую во многих своих пректах. Однако один из моих проектов не пропускается из-за того что в вашем файле air-datepicker.js присутствует кирилица https://prnt.sc/oyrPC8O0QvFY. Из-за этой строки меня по валидации не пропускают

**Comment by t1m0n** [comment]
Добрый день! Не работает ссылка, но думаю что это из-за русской локализации. Она включена по умолчанию в бандл. Вы можете сделать форк, и поставить любую другую локализацию по умолчанию в своей сборке
