### ISSUE TITLE
Issues in Modal

### ISSUE THREAD

**Issue by Thomas89** [t1m0n/air-datepicker#5]
Hey! 
It does not work when I use it in a Modal..
I have tried for several hours now, and get the following error:
"Uncaught TypeError: Datepicker.Body is not a function" @ line 158
( this.views[this.currentView] = new Datepicker.Body(this, this.currentView, this.opts); )...
Is there anyone who knows how to solve the problem?

**Comment by t1m0n** [comment]
Hi!
Do you mean you are using it with modal window plugin? Can you provide an example or jsfiddle maybe?

**Comment by Thomas89** [comment]
Exactly!
My page is very complicated, so it becomes a little difficult ..
I use this plugin to load my page in a modal window through ajax ( in my case, i using the last link in that example "JS triggered (all the options!)")..
( http://codepen.io/pixelthing/pen/khFav ).

If you look at line 62 (in the JS File) you can see how my Modal Window look like, and that's where it causes trouble for me..
Excuse my bad explanation, are not great at English

**Comment by t1m0n** [comment]
If you are using ajax, then you must init datepicker after ajax request is completed and html has been inserted to modal window. I suppose you are trying to init it erlier or before request is completed.

In your case, try to init datepicker in `.load()` callback function - http://c2n.me/3rWXkCk

**Comment by Thomas89** [comment]
it still not work..
My "index.php" look like this:
```html
<html>
	<head>
	<link href="Plugin/css/datepicker.min.css" rel="stylesheet" type="text/css"></head>
	<body>
	<!-- my countent etc here + link to my Modal Windows -->
	<script src="jQuery.js"></script>
	<script src="Plugin/uSwitch.js"></script>
	<script src="Plugin/datepicker.min.js"></script>
	<script src="Plugin/datepicker.en.js"></script>
	</body>
</html>
```
And my loaded-through-ajax-page.php i use look like this:
```html
	<!-- ajaxpage.php start -->
	<input type="text" id="nf_selectmm" class="datepicker-here" data-language='en' data-min-view="months"  data-view="months" data-date-format="MM yyyy" />
	<!-- my countent etc here -->
	<script src="jQuery.js"></script>
	<script src="Plugin/datepicker.min.js"></script>
	<script src="Plugin/datepicker.en.js"></script>
```
 ![http://clip2net.com/s/3rZvxR4](http://clip2net.com/s/3rZvxR4)
![http://clip2net.com/s/3rZvPgy](http://clip2net.com/s/3rZvPgy)

**Comment by t1m0n** [comment]
I've created a pen with plugin you use, check it here - http://codepen.io/t1m0n/pen/zrBqWz. I just added a huge z-index to datepicker to make it visible over the modal window, and add manual initialization in JS file on 232 line. Html which is loaded with ajax located here - http://codepen.io/t1m0n/pen/MKeyXj. Everything works fine.

**Comment by Thomas89** [comment]
IT WORKS!! 
Thank you so much, I really appreciate your help !!

A small question just .. How do I get it to display the current date onload ?
My code looks like this , and I want it to display the current date when the page loading is finished ..

```html
<input type='text' class='datepicker-input' data-min-view="months" data-view="months" data-date-format="MM yyyy">
```
and
```html
<input type='text' class='datepicker-input'>
```

**Comment by t1m0n** [comment]
Glad it helped.
To display current date, you must initialize plugin manually in js, and select current date.

```js
// Initialize datepicker and save its instance in `dp`
var dp = $('.datepicker-input').datepicker().data('datepicker');

// When just use method .selectDate(), to select desirable date.
dp.selectDate(new Date()) // Will select current date;
```

I have modified previous example on CodePen to show how it works. (http://codepen.io/t1m0n/pen/zrBqWz)

**Comment by t1m0n** [comment]
Closed due to inactivity

**Comment by HARIPRASADHARI** [comment]
Hi,
I am also facing same issues.Above code pen links are not working.Can you update that.

**Comment by ibnbay99** [comment]
Hi @t1m0n , can u produce the example again? the latest example page is gone...

**Comment by joy777** [comment]
Мне тоже самое нужно! Как провести инициализацию чтобы вывести календарь в модальное окно.

**Comment by eevyaj03** [comment]
Pls any update. I want to show the Air datepicker in the modal. Thanks

**Comment by alexovn** [comment]
Hello, everyone. You need to style ".air-datepicker-global-container" class. Add "z-index: 2000" to it.
