### ISSUE TITLE
Documanetation missing scss implementation

### ISSUE THREAD

**Issue by fakerdog1** [t1m0n/air-datepicker#500]
I would strongly suggest adding a paragraph about importing the datepicker in the scss file. I spent 2 hours trying to figure out where my javascript was wrong, because my calendar did not generate. 2 hours later, turns out I had to import the scss to my relevant file. Nowhere in the doc is this mentioned so I suppose there have been other devs who had the same issue.

**Comment by t1m0n** [comment]
You don't have to include `scss` files. You need only `.css` file for styling the calendar and there is an example of code on main documentation page at bottom with `.css` file included.
