### ISSUE TITLE
Значение при выборе диапазона дат.

### ISSUE THREAD

**Issue by Maksim63** [t1m0n/air-datepicker#51]
Здравствуйте Тимофей!
Большое спасибо за плагин. Есть пара вопросов.

1. Можно ли в качестве опции altField использовать span, p или div ?
2. Если altfield не задан, а datepicker вешается на строчный или блочный элемент, как в этом случае получить результат выбора. Иными словами как присвоить переменной результат выбора, чтобы потом его оформить по своему и отобразить в нужном месте.
3. если выбирается диапазон дат (range) или две даты (через multipleDates со значением 2), это получается одна строка (переменная), можно ли как-то результат присваивать двум переменным ? или только через парсинг строки ?

**Comment by t1m0n** [comment]
Добрый день Максим, спасибо за ваш отзыв.

1 - К сожалению нет.
2 - Можно присвоить значение выбранной даты в функции обратного вызова `onSelect` и отрисовать ее в любом нужном вам элементе:

```javascript
<div class="my-datepicker"></div>
<span class="result"></span>

$('.my-datepicker').datepicker({
    onSelect: function (fd) {
        var result = fd;
       $('.result').html(result)
    }
})
```
3 - Вторым аргументом передается массив выбранных дат в формате `Date()`. Можно получить все даты оттуда и отформатировать как вам нужно:

```javascript
<div class="my-datepicker"></div>
<span class="result"></span>

$('.my-datepicker').datepicker({
    multipleDates: true,
    onSelect: function (fd, dates, inst) {
        var $res = $('.result'),
            string = 'Выбранные даты: ';

        dates.forEach(function (date) {
            string += date.getDate() + ' ';
        })

        $res.html(string);
    }
})
```

Также попробуйте обновиться до последней версии 2.0.2, в ней исправлен `onSelect` - как раз для третьего кейса.

**Comment by Maksim63** [comment]
Здравствуйте Тимофей.

есть несколько вопросов. код для примера. весь код и стили не привожу, для краткости.

```
<div id="myCalendar>
   <button type="button" id="dateaccept">OK</button>
</div>
  <span class="result"></span>

var Calendar = $('#myCalendar').datepicker({
    altField: "#view",
    altFieldDateFormat: "MM yyyy",
    view: "months",
    minView: "months",
    dateFormat: "MM yyyy",
    range: "true",
    multipleDatesSeparator: " - ",
    
    onSelect: function (fd) {
        var result = fd;
        $("#dateaccept").click(function(){
            $('.result').html(result);
        })
    }
})

```
календарь вызывается из модального окна, по нажатию на "ок" выбранные значения отрисовываются в .result. можно выбрать одну дату, можно диапазон. в данном случае я использую настройки для выбора месяцев. всё отображается хорошо. Но как только я пытаюсь отправить значение fd с помощью AJAX- запроса на сервер, то приходят две строки - отдельно первый выбранный месяц, и отдельно диапазон первый-последний месяц. 
1. как можно от этого избавится ? при этом на экран выводится всё отлично.
2. если без перезагрузки страницы вызвать календарь снова и выбрать ещё один диапазон - то на экарне выводится всё в порядке, в AJAX-запросе уже уходит 3 строки, предыдущие две и новая. как сделать очистку выбранных данных при каждом вызове календаря ?

**Comment by maxnagorniy** [comment]
Привет. 
У меня есть вопрос: 
- Если выбирается диапазон дат(range), но между ними есть дата, которая disabled, можно в таком случае запретить выбор дат ? Долго не могу найти решение

**Comment by ATM-NET** [comment]
Привет
Возможно ли заменить ползунки установки времени на более привычные пользователям окошки со стрелками? Или окошки без стрелок :) но лишь бы не ползунки. У меня директор в ярость приходит когда их видит...

**Comment by t1m0n** [comment]
Привет, к сожалению, ползунки убрать нельзя.

чт, 29 авг. 2019 г. в 14:05, ATM-OWNER-ACCOUNT <notifications@github.com>:

**Comment by nordmarin** [comment]
> Привет.
> У меня есть вопрос:
> 
> * Если выбирается диапазон дат(range), но между ними есть дата, которая disabled, можно в таком случае запретить выбор дат ? Долго не могу решить

Решили вопрос?
