### ISSUE TITLE
Wrong time displayed with selectedDates

### ISSUE THREAD

**Issue by pvictor** [t1m0n/air-datepicker#510]
Displayed time is **AM** but selectedDates provided is **PM**

![image](https://user-images.githubusercontent.com/4415580/206225744-ec4e7792-8fef-4bb1-ade0-b0a22580b6df.png)

Here code to reproduce : 

```js
import AirDatepicker from "air-datepicker";
import en from "air-datepicker/locale/en";
import "air-datepicker/air-datepicker.css";

let options = {
  locale: en,
  selectedDates: [new Date("2022-12-07 16:00:00")],
  timepicker: true
};

let dp = new AirDatepicker("#dp", options);
```

Tested with version 3.3.1

Link to sanbox : https://codesandbox.io/s/vigilant-kilby-t77k4e

**Comment by t1m0n** [comment]
Thanks for the bug report!
