### ISSUE TITLE
Not working timeFormat HH

### ISSUE THREAD

**Issue by paulvales** [t1m0n/air-datepicker#512]
Use jquery-3.1.1.min.js
My config :
`new AirDatepicker('#arrival', {
    timepicker: true,
    timeFormat: 'HH:mm'
});`
but in calendar timepicker hours showing as 12-format, in #arrival as 24-format
[Screenshot](https://disk.yandex.ru/i/pzAouqand1CU_g)

**Comment by t1m0n** [comment]
Thanks for the bug report!
