### ISSUE TITLE
Buttons: Get them to display at the side.

### ISSUE THREAD

**Issue by tarwin** [t1m0n/air-datepicker#514]
First, thank you. Love the picker!

Is there any way to get buttons to display at the side of the widget?

I'm trying to make a "fuzzy" date picker, but it's hard to add more than a few buttons if they are below.

Example:
https://codesandbox.io/s/fuzzy-date-picker-pmcc5g?file=/index.html

**Comment by tarwin** [comment]
I tried to get it to run locally for dev to see if I could implement myself but couldn't get it to run :( something wrong with installing SASS.

Which Node version etc is used for dev ?

**Comment by t1m0n** [comment]
Hey @tarwin, thanks for the response! You could easily place buttons on the right side of the calendar using `css-grid` properties. I've made an example for you https://codesandbox.io/s/fuzzy-date-picker-forked-7x7cc5?file=/src/index.js

**Comment by tarwin** [comment]
Thanks @t1m0n - that's a good solution. I was heading in that direction too, but was having problems with getting the correct CSS var 😄 

Do you think it would be a good idea to add this as an option? Maybe bottom/right/left/top ?
