### ISSUE TITLE
Impossible to use after  $datepickersContainer is removed from the DOM

### ISSUE THREAD

**Issue by mholt** [t1m0n/air-datepicker#516]
I have an SPA where the `<body>` is replaced on page transitions, and a new date picker needs to be created. Unfortunately this makes it impossible to use AirDatepicker after a page with an AirDatepicker is replaced with a new page that also has an AirDatepicker, because the lib only allows creating a container element once:

https://github.com/t1m0n/air-datepicker/blob/76235dc112142089f74603eeb19ebc1f02e6aa4b/src/datepicker.js#L37-L44

This results in an error when clicking the input to open the date picker, because `this.$datepicker.offsetParent` from this line:

https://github.com/t1m0n/air-datepicker/blob/76235dc112142089f74603eeb19ebc1f02e6aa4b/src/datepicker.js#L710

is null, so it goes boom :boom: on this line:

https://github.com/t1m0n/air-datepicker/blob/76235dc112142089f74603eeb19ebc1f02e6aa4b/src/datepicker.js#L742

I think a more robust approach would be to allow creating the container again if it does not still exist in the DOM.

Edit: I should clarify, this is only an issue when `container` is _not_ specified in the options when constructing a new AirDatepicker. The problem is that I can't pass in a container because at the time of constructing it I do not know where it will go yet.

**Comment by t1m0n** [comment]
@mholt hi, interesting case) I will figure something out.

**Comment by t1m0n** [comment]
Added extra check if container still exists on init, should do the trick

**Comment by mholt** [comment]
@t1m0n Oh awesome!! I will try it as soon as I can, thank you!

**Comment by mholt** [comment]
Finally had a chance to test this. It seems to work for me! Thank you very very much! :100:

**Comment by t1m0n** [comment]
@mholt Oh great! Glad to hear that it worked for you. 
Also thanks for a nice feedback, I've must have missed the message :)
