### ISSUE TITLE
air-datepicker + webpack

### ISSUE THREAD

**Issue by MaximShvec** [t1m0n/air-datepicker#519]
Привет, установил последнюю версию air-datepicker и столкнулся с такой ошибкой
**SyntaxError: F:/work/euroled/public/HTML/node_modules/air-datepicker/air-datepicker.js: Unexpected token (1:7295)**

Не подскажешь, что может быть не так ?
Проект на webpack
![image](https://user-images.githubusercontent.com/26522380/213252262-3ef25c68-f448-4a14-9d90-e13f295587a2.png)

![image](https://user-images.githubusercontent.com/26522380/213252196-b07681c1-696a-482d-93f4-347375934d98.png)

Сама ошибка выглядит так
![image](https://user-images.githubusercontent.com/26522380/213252484-b088ad3a-553b-4d71-8aa9-2be8de7de9e6.png)

**Comment by t1m0n** [comment]
Привет! Не правильно собралось видимо( думаю исправлю на следующей неделе. Спасибо за баг репорт.

**Comment by t1m0n** [comment]
@MaximShvec попробуй версию 3.3.5, должно заработать.
