### ISSUE TITLE
select date in vue 2

### ISSUE THREAD

**Issue by fmarz96** [t1m0n/air-datepicker#522]
Hi @t1m0n 
I am trying to select a date(using air-datepicker) on vuejs 2 but when I continue to focus another input that hasnt got datepicker is clears the selected date. What should I do to avoid this? Taking into account that the inputs that have datepicker have the readonly attribute applied.
Thanks!

**Comment by t1m0n** [comment]
Hi @fmarz96, it doesn't seems like problem in datepicker. Could you please provide an live example on [codesandbox](https://codesandbox.io)? Thank you.

**Comment by fmarz96** [comment]
Hi!
I finally solved it on my own. The v-model attribute was the problem. That was what clearing the input value after filling other inputs.Thanks!
