### ISSUE TITLE
It doesn't work before the DOM is created.

### ISSUE THREAD

**Issue by leadream** [t1m0n/air-datepicker#53]
Hello,first thanks for your great job.When I use it,I find an issue on it.
First I init the datepicker:
`
$('.datepicker-shipping').datepicker({
    language:'zh'
});
`
then I append a 'input' in html:
`
$('<input>',{class:'datepicker-shipping'}).appendTo('body');
`
But it doesn't work.
Expect your reply,thanks.

**Comment by t1m0n** [comment]
Hello. Well its not suppose to work this way. You always have to create DOM element first then initialize plugin. It is not about plugin, but how js and html work.

**Comment by leadream** [comment]
ok , thanks for your answer.
