### ISSUE TITLE
Use `toggleSelected` as function

### ISSUE THREAD

**Issue by samirsayyaad** [t1m0n/air-datepicker#534]
Hi,

It's impossible to select the same month again after selecting multiple months. 

My config: `{ toggleSelected: false, range true }`

In the event that the user wants to cancel their current selections, they can pick another month. However, imagine if the user picked January-Feb and then suddenly decided to select only January.

https://user-images.githubusercontent.com/113973757/229452245-c1679224-2019-4790-9df0-bc4db226cfd1.mov

**Comment by t1m0n** [comment]
Well, you should set `toggleSelected: true` in this case )

**Comment by samirsayyaad** [comment]
Hi @t1m0n,

Thanks for answering. 

If I set `toggleSelected: true`, I can't choose just one month by double clicking on it. So, I want to have `toggleSelected` be `false` and can deselect the selected month as you can see in the video.

**Comment by t1m0n** [comment]
@samirsayyaad now you can use `toggleSelected` as a function and create any behaviour you want )
