### ISSUE TITLE
How to initialize multiple datepickers with identical options?

### ISSUE THREAD

**Issue by LapinskasL** [t1m0n/air-datepicker#535]
I will have a variable number of date fields on the page. They all need to be initialized the same way with the same settings. I thought I would be able to just do `new AirDatepicker(".class-name");` and initialize all the elements with the class `class-name`. However, only the first element works when I initialize it in this way. 

Now if I initialize them separately with unique IDs then it works. But I don't want to do that because I might have many fields that need to be initialized with the plugin.  I'd rather just run it once.

How can I solve this?

[Sample code with the issue](https://jsfiddle.net/09kjc63b/). If you click on the End Date field, you will see the datepicker does not open like it does for the Start Date field.

**Comment by t1m0n** [comment]
You should grab all required components with `getQuerySelectorAll` and then loop through them and initialize datepicker separately for each element.

```javascript
const $els = document.querySelectorAll('.elems');

$els.forEach(el => {
  new AirDatepicker(el)
});

```
