### ISSUE TITLE
no variable/method to get "start" and "end" date from calendar.

### ISSUE THREAD

**Issue by navdeepghai1** [t1m0n/air-datepicker#536]
There should be a way to get "start" and "end" date of current calendar view.

![Screenshot 2023-04-10 at 1 48 14 PM](https://user-images.githubusercontent.com/30634335/230960839-043c5858-df03-4e99-8873-3d78eb3d621f.png)

**Comment by t1m0n** [comment]
Added method `getViewDates` in last release - https://air-datepicker.com/ru/methods?scrollTo=getViewDates(view?) which should return array of all dates that should be visible in calendar. You can use this to get first or last date.

**Comment by mjahid98** [comment]
Is there a way to show two months together in the calendar view? Something similar to the screenshot. Also, is there a way to switch to a different month programmatically with JS?
![image](https://github.com/t1m0n/air-datepicker/assets/47502776/af1cf838-a19e-4e7e-b544-186ee7fc1138)

**Comment by t1m0n** [comment]
@mjahid98 unfortunately no. You can use https://air-datepicker.com/methods?scrollTo=setViewDate to switch between different months
