### ISSUE TITLE
Use the browser-provided Intl libraries

### ISSUE THREAD

**Issue by sandstrom** [t1m0n/air-datepicker#538]
I think for any date picker that want to make maintenance somewhat easy, it should rely on the browser for localisation.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat (and others in the Intl group)

It should also likely be built on Temporal, the upcoming replacement for `Date` in JS:

https://github.com/js-temporal/temporal-polyfill

Just wanted to suggest these two things. Feel free to close this issue.

Thanks for a great project! 🏅

**Comment by t1m0n** [comment]
@sandstrom Thanks for advices, will think of 'temporal' when it is will be a standard 😉

**Comment by simon04** [comment]
Heads up. As of 2026, Temporal is natively supported by Firefox, Chromium. Safari support is coming. 

Ref:
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal
* [Temporal: The 9-Year Journey to Fix Time in JavaScript](https://bloomberg.github.io/js-blog/post/temporal/)
