### ISSUE TITLE
Установка диапазона определённой длины после клика на пикер

### ISSUE THREAD

**Issue by deavy** [t1m0n/air-datepicker#54]
Привет! Отличный плагин, но есть одна небольшая проблема, которую я не могу решить: у меня включена опция `{range: true}`, есть дата начала диапазона и длительность диапазона. Можно ли каким-нибудь образом после инициализации плагина установить новые даты и новый диапазон?

Я думал сделать это в коллбеке  `onSelect: function (formattedDate, date, inst) { ... }`, но в итоге сваливаюсь в беконечный цикл по вполне очевидным причинам (Uncaught RangeError: Maximum call stack size exceeded)

**Comment by t1m0n** [comment]
Привет!
В этом случае можно использовать метод `.selectDate()` и передать в него массив нужных дат:

```javascript

<input id='dp' type='text' />

<script>
    var dp = $('#dp').datepicker({range: true}).data('datepicker');
    
    dp.selectDate([
        new Date(2016, 4, 10),
        new Date(2016, 4, 15)
    ]);
</script>
```

**Comment by deavy** [comment]
Да, таким образом я инициализирую сам пикер после загрузки страницы, показываю заранее выбранную юзером дату.

А каким образом это можно сделать при клике по самому пикеру? Скажем, у меня сначала был диапазон с 10 по 15, а потом юзер хочет выбрать такой же диапазон с 20 по 25. То есть я хотел бы двигать диапазон сразу при первом клике в календарь (клик → диапазон целиком сдвинулся).

Просто когда я делаю это в коллбеке `onSelect()`, то там уже на момент инициалзиации плагина всё уходит в бесконечный цикл.

**Comment by t1m0n** [comment]
Ага, примерно понятно что требуется. Можно попробовать немного костыльным способом сделать, чтобы не было бесконечного цикла:

```javascript
$('#dp').datepicker({
    onSelect: onSelect
});

function onSelect (fd, d, inst) {
    inst.update({
        onSelect: ''
    });

    inst.selectedDates = [];
    inst.selectDate([new Date(2016, 4, 10), new Date(2016, 4, 15)]);

    inst.update({
        onSelect: onSelect
    })
}
```

Здесь при клике всегда будет выбираться диапазон от 10 до 15 числа. Важно сбрасывать `selectedDates` потому что в нем уже будет храниться выбранная ранее дата. Если этого не делать то будет активироваться только последняя дата в массиве.

**Comment by deavy** [comment]
Хорошо, спасибо, попробую реализовать.
