### ISSUE TITLE
Пример работы с react&typescript + установка динамического значения.

### ISSUE THREAD

**Issue by DmitrySheklein** [t1m0n/air-datepicker#547]
@t1m0n, привет, можешь помочь разобраться? Уже 2й день сижу с интеграцией в проект. Совсем не нашёл примеров использования библиотеки с react typescript, правильно ли я типизировал?

Не разобрался как правильно работать с динамическим значением, которое приходит извне (дата с бека в формате "10.06.2023").
И также хотелось бы оставить ручной ввод в поле (сейчас он стирает только один символ).

Вот пример кода:
https://codesandbox.io/s/relaxed-panka-2z7lph?file=/src/react-datapicker.tsx

**Comment by t1m0n** [comment]
@DmitrySheklein привет! пока нет возможности, гляну завтра, после завтра.

**Comment by t1m0n** [comment]
@DmitrySheklein чуть изменил твой пример https://codesandbox.io/s/vibrant-resonance-wsphn6 . Если хочется чтоб можно было в инпуте писать дату, то лучше разделять пропсы на два колбека - один на инпут, другой на календарь. Добавил в пример возможность выбирать дату при изменении инпута - здесь тоже есть небольшой ньюанс - нужно отключать навигацию клавиатуры, чтоб пользователь мог стрелочки использовать для перемещению по инпуту.

**Comment by DmitrySheklein** [comment]
@t1m0n, спасибо! то что нужно
