### ISSUE TITLE
Get datepicker instance, no way?

### ISSUE THREAD

**Issue by luca-sacco** [t1m0n/air-datepicker#548]
For automation tests written in Cypress, I'm looking for a way to avoid doing complicated logic clicking on the various datepicker functions to select a date, but rather I was looking for a way to fetch the datepicker instance from the HTML element and then call the .selectDate() method.
Is there any way to do this?

Thanks!

**Comment by GamendeBrian** [comment]
Using `var date_from = new AirDatepicker('#date-from', {})` I can later on just use `date_from.selectDate(moment(date))`

**Comment by luca-sacco** [comment]
> Using `var date_from = new AirDatepicker('#date-from', {})` I can later on just use `date_from.selectDate(moment(date))`

Tests written in Cypress run in a context where the AirDatepicker lib is not installed. So this can't work...
