### ISSUE TITLE
No placeholder option

### ISSUE THREAD

**Issue by jon-mcclung-fortyau** [t1m0n/air-datepicker#549]
When I use this the placeholder is always "mm/dd/yyyy" but I want the placeholder to be something totally different and dynamic. I set a placeholder on the input but that is ignored and there is no placeholder option on AirDatepicker to take advantage of. This feature would be a good thing to add.

**Comment by t1m0n** [comment]
AirDatepicker doesn't control placeholder behaviour on input. It should work fine. Could you, please, create a live example of what you are describing? 
I'am using native placeholder on documentation page, and there are no problems with that - https://air-datepicker.com/ru/examples

**Comment by jon-mcclung-fortyau** [comment]
I see, it seems to be happening because I'm using type="date" which I need to do for other reasons. I will close this issue because your library is not the cause of the problem.
