### ISSUE TITLE
how can I set 2 range dates with js code in air-datepicker?

### ISSUE THREAD

**Issue by sergeynilov** [t1m0n/air-datepicker#554]
Remaking  code from air-datepicker (with range = true ) 2.2.3 into  v3.3.5 I did not find how can I set 2 range dates with js code.

Clicking on button I need to add sevaral days to first date, like I did under 2.2.3:

```
       const dateRangeInput = $('.date-range');
       dateRangeInput.data('datepicker').selectDate([date1, date2]);
```

But reading docs at
https://air-datepicker.com/docs
I did not find how can I dop this under v3.3.5 ?

**Comment by sergeynilov** [comment]
After reading the docs it looks like that I need to cretate a new instance of AirDatepicker, when I need to set selectedDates 
programmatically on some event(not only when AirDatepicker is inited), like :

```
                var dp = new AirDatepicker('.date-range', {
                    multipleDates: true,
                    range: true,
                    multipleDatesSeparator: ' - ',
                    selectedDates: [date1, date2]
                })

```
I did not find any other way, the same as when I need to run onSelect method by clicking on the button of the form...
I dislike this way, how can I do it in better way?

**Comment by t1m0n** [comment]
If I understood you correctly, you could still use the same way to select multiple dates as before - 

```
const dp = new AirDatepicker('.date-range', {range: true});

dp.selectDate([date1, date2])
```
