### ISSUE TITLE
Custom navigation button image

### ISSUE THREAD

**Issue by DavidPetrasek** [t1m0n/air-datepicker#560]
The current arrows are defined as 
`<svg><path ...></path></svg>`

It should be possible to provide a custom images. For example:

```
import img_prevButton from './img_prev.png';
import img_nextButton from './img_next.png';

new AirDatepicker(document.querySelector('.date'), 
	{
    	     buttonPrevImg: img_prevButton,
             buttonNextImg: img_nextButton
	});
```

And the default svg's cannot be scaled by CSS:
```
{
     width: 2em;
     height: 2em;
}
```

**Comment by t1m0n** [comment]
You always could use somethink like `prevHtml: <img src="my-img.png">`

**Comment by DavidPetrasek** [comment]
It works now.
I was searching for "button" in the documentation and I couldn't find it.
I propose to rename it so it contains the word "button".
