### ISSUE TITLE
Ability to select date range on same day

### ISSUE THREAD

**Issue by fulit103** [t1m0n/air-datepicker#563]
Currently, I cannot select the end date range on the same day, a few hours later than the start date - it's minimum 1 day in-between.

I saw this thread related, apparently is solved but i cannot select the end date range on the same day

https://github.com/t1m0n/air-datepicker/issues/74

I created this wrapper for ember https://github.com/fulit103/ember-air-datepicker, Currently I'm using this library on Jebbit.com platform, could you suggest me a solution?

**Comment by fulit103** [comment]
My bad, I used  toggleSelected parameter:

toggleSelected: ({ datepicker }) => {
        if (self.args.range == true) {
          if (datepicker.selectedDates.length == 2) {
            return true;
          }
          return false;
        }
        return true;
}
https://github.com/fulit103/ember-air-datepicker/pull/6/files

thanks

**Comment by ethaniel** [comment]
This solution is not very intuitive for the user, unfortunately. For example, when there is a range which is already selected, and the user wants to just use the only the first or the last day of the range (and clicks on them) - nothing happens.
