### ISSUE TITLE
Auto Close after Trigger from external button

### ISSUE THREAD

**Issue by chalamministries** [t1m0n/air-datepicker#565]
so I'm triggering the air datepicker from a button. But if I click anywhere else and not on a date, it does not close. If i click on the second button that opens a different air datepicker, it doesnt close the other one either. How can I make it autoclose even though I have autoclose: true set

**Comment by t1m0n** [comment]
You should use `hide` method to close in manually  - https://air-datepicker.com/methods?scrollTo=hide
