### ISSUE TITLE
Auto Hide Date picker

### ISSUE THREAD

**Issue by arj060892** [t1m0n/air-datepicker#57]
How can i hide the calendar control after selection of a particular date

**Comment by t1m0n** [comment]
You should use `{autoClose: true}` if you want to hide datepicker after selecting date. Or check for selected date in `onSelect` event and hide calendar manually:

**Hide if selected date equals to 4**

```javascript
<input id='dp' type='text' />

<script>
    $('#dp').datepicker({
        onSelect: function (fd, d, calendar) {
            if (d.getDate() == 4) {
                calendar.hide()
            }   
        }
    })
</script>
```

**Comment by chetanbane** [comment]
It won't work for me I  have just change small code &  it works

var myDatepicker = $('#dob').datepicker().data('datepicker');
  $('#dob').datepicker({
    onSelect: function (fd, d, calendar) {
        if (d.getDate() != '') {
          myDatepicker.hide()
        }   
    }
  });
