### ISSUE TITLE
API weirdness

### ISSUE THREAD

**Issue by scriptingstudio** [t1m0n/air-datepicker#581]
While testing API I create a new button
```javascript
let buttonOK = {
	content: 'OK',
	className: 'custom-button',
	onClick: (dp) => {
		dp.hide();
		dp.done();
	}
}
```

After click on the button the console error comes up 
```javascript
Uncaught TypeError: dp.done is not a function
at onClick 
at HTMLButtonElement.<anonymous> (air-datepicker.js:1:19640)
```

If I use just `dp.done;` it will work without errors, although the doc states to use `done` as function.
Is it a possible bug or what?

**Comment by t1m0n** [comment]
Hello! There is no such method and that is why you get an error. Maybe there is an error in documentation, could you please tell me where did you find about the need to use this method?

**Comment by scriptingstudio** [comment]
![image](https://github.com/t1m0n/air-datepicker/assets/17237559/064727f4-f3dd-4e3f-9f86-cbaf9984c88e)

**Comment by t1m0n** [comment]
@scriptingstudio `done` here is a callback which is passed through parent function argument and is not a method of AirDatepicker. Also it is used only in such situation when you need to control position manually.

**Comment by scriptingstudio** [comment]
Should I use `done` in a button handler after `hide()` or just `hide()`?

**Comment by t1m0n** [comment]
@scriptingstudio No, you should not
