### ISSUE TITLE
параметр {silent: true}  игнорируется при multipleDates / range: true .

### ISSUE THREAD

**Issue by 3JlblgEHb** [t1m0n/air-datepicker#583]
Если задавать параметр {silent : true } при использование в обычном режиме то все отрабатывает ка надо . 
но при использование {silent : true } в режиме range или  multipleDates то в таком случае все равно срабатывает триггер **onSelect**.   возможно кто то сталкивался с такой проблемой ?

**Comment by t1m0n** [comment]
@3JlblgEHb не получается воспроизвести, можете сделать живой пример с багом?

**Comment by 3JlblgEHb** [comment]
@t1m0n  это будет немного сложнее  так как я использую библиотеку для создания плагина на платформе bubble.io 
ссылка на [демо](https://zeroqode-demo-27.bubbleapps.io/version-test/ga_picker_pro) 
<img width="787" alt="image" src="https://github.com/t1m0n/air-datepicker/assets/88478943/81a9e5cd-5863-4bb3-ba34-73aa80b4081b">

на скрине пример используемых опции. 
во втором скрине используемая функция instance.data.onSelect()   для опции oneSelect. 
для наглядного примера можно увидеть в консоле что oneSelect() срабатывает ровно столько раз сколько дат указано в массиве для selectedDates. 
 
<img width="485" alt="image" src="https://github.com/t1m0n/air-datepicker/assets/88478943/393c6844-ad00-4ec8-b898-c640dc06541f">

как я понимаю документацию если использовать опции "silent: true " и "updateTime: false"  то в таком случает опция " oneSelect " которая отрабатывает функцию не должна тригерится ?

**Comment by t1m0n** [comment]
@3JlblgEHb не совсем так - `{silent: true}` нужно передавать непосредственно в метод `selectDate`, а не в параметры самого календаря.

```js
const dp = new AirDatepicker(...);

dp.selectDate(new Date(), {silent: true})

```

**Comment by 3JlblgEHb** [comment]
@t1m0n  в примере это именно так и реализовано  , можно увидеть это в первом скрине .   я передаю в метод `selectDate` settings . в котором и указаны эти параметры `{silent: true}` .  в идентичных условиях для работы в формате единичного выбора дат все работает так ,  но как только мы используем это в работу со списком дат или рэндж , мы получаем отработку `oneSelect` ровно столько раз сколько дат мы передаем .

**Comment by t1m0n** [comment]
@3JlblgEHb скорее всего это происходит из-за того, что вы передаете `selectedDates` в метод `update`. Попробуйте выделить их в отдельную переменную и активировать их отдельно в методе `selecteDate`.

Но кейс хороший, надо добавить возможность передавать `silent` в `update`.

**Comment by 3JlblgEHb** [comment]
@t1m0n  Да ваш вариант сработал . спасибо большое за помощь , быстрые ответы и поддержку !!!

**Comment by t1m0n** [comment]
Добавил silent в update
