### ISSUE TITLE
I set < input > in a scrollable < div >,the datepicker will stay there when it scrolling.

### ISSUE THREAD

**Issue by leadream** [t1m0n/air-datepicker#59]
Now I set the <input> as datepicker trigger.
The < input > is in a scrollable < div > , when I am scrolling the div,the datepicker will stay there , not following.
```html
<div style="height:200px;overflow-y:auto;">
    <input class="datepicker-here">
</div>
````

**Comment by t1m0n** [comment]
You must handle it by yourself, the plugin doesn't know when it's parent is scrolling. You can try to use `update()` method:

```javascript
<div class="container">
    <input type="text" id="dp"  />
</div>

<script>
    var dp = $('#dp').datepicker().data('datepicker');

    $('.container').on('scroll', function () {
        dp.update();
    })
</script>
```

But datepicker's container is placed in `<body>` tag, so it's position is relative to it. And if calendar will update its position, it will stay visible even if `<input>` is out of viewable area, it can't be fixed now.

**Comment by leadream** [comment]
thanks for your answer.Really great plugin.

**Comment by mholt** [comment]
Sorry to necro this, but still seems relevant: could the date picker's container be placed closer to the element it is attached to instead of always the `<body>`? Or maybe we could configure where its container should go?
