### ISSUE TITLE
TypeError при destroy()

### ISSUE THREAD

**Issue by johnnygrossamer** [t1m0n/air-datepicker#600]
Иногда случается ошибка при вызове destroy(), 
- air-datepicker подключен как пакет в package.json
- ошибка случается только в production версии после сборки, в режиме разработки ошибок нет
- altFieldDateFormat и altField не используются в проекте вообще

Ошибка:
**Uncaught TypeError: Cannot destructure property 'altFieldDateFormat' of 'e' as it is null**

Часть кода из сборки в котором случается ошибка:
`(()=>{let{opts:e,$altField:t,locale:{dateFormat:o}}=this,{altFieldDateFormat:n,altField:i}=e;...`

**Comment by t1m0n** [comment]
Спасибо, надо глянуть

**Comment by elYanuki** [comment]
afaik this error occurs every single time a picker is destroyed

```
let picker = new AirDatepicker(input)
console.log(picker)
picker.destroy()
```

in this case I encounter the error:
`Cannot destructure property 'showEvent' of 'this.opts' as it is undefined`

When adding more properties i additionally get the same error as OP even though i never used the `altFieldDateFormat` option

**Comment by t1m0n** [comment]
@elYanuki I should definitely fix this)

**Comment by johnnygrossamer** [comment]
> Спасибо, надо глянуть

Позвольте уточнить стоит ли ожидать в ближайшее время исправления этой ошибки, честно говоря в bugreport тысячи этих ошибок, и на каждую я дергаюсь)

**Comment by t1m0n** [comment]
Fixed in 3.5.1 - added `isDestroyed` property - which should be manually checked if some of methods will be called after datepicker has been already destroyed. Also fixed some errors which were thrown after calling the `destroy()`
