### ISSUE TITLE
Time only picker does not use the current form field value

### ISSUE THREAD

**Issue by tjveldhuizen** [t1m0n/air-datepicker#606]
When I define my picker as in [this codepen](https://codepen.io/tjveldhuizen/pen/vYMbopG), the default value in the picker is the current time, instead of the time set in the value property of the input.

Is this a bug, or is it expected and should I do something with `selectDate()` and an event listener to handle manual changes in the input?

**Comment by t1m0n** [comment]
It is not a bug, datepicker doesn't check input value. In your case you could define selected date in options like so


```javascript
new AirDatepicker("#app", {
  onlyTimepicker: true,
  timepicker: true,
  selectedDates: ['2024-04-26T10:11']
});
```

**Comment by tjveldhuizen** [comment]
OK, if it's a feature I'll close the issue.
