### ISSUE TITLE
Missing position in type definition file

### ISSUE THREAD

**Issue by SennaSanzo** [t1m0n/air-datepicker#626]
Hello, 

I think the 'center' position is missing from AirDatepickerPosition type declaration. It forces to convert the position to any like so:

```typescript
new AirDatepicker(inputEl, {
      position: "right center" as any,
})
```

**Comment by t1m0n** [comment]
Hello! You should use 'right' for that purpose.

**Comment by SennaSanzo** [comment]
Sorry but it seems that right doesn't produce the same render in terms of css. Maybe it is a compability issue with my own design but if I only use the "right" position in TypeScript the airdatepicker is broken and doesn't appear next to my input. For now I use the dirty soltution I speficied in my initial post and I will come back to you If I have more time to investigate on this... Thank you
