### ISSUE TITLE
Inconsistency between AirDatepicker.visible and checkVisibility

### ISSUE THREAD

**Issue by MagnusOxlund** [t1m0n/air-datepicker#633]
I ran into an issue implementing a toggle switch to show and hide the calendar.

The `visible` instance property returns a different result than running `checkVisibility` directly on the calendar element (`$datepicker`). I would expect the two approaches to have the same outcome.

Here's a test case:

```HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="modulepreload" href="https://cdn.skypack.dev/pin/air-datepicker@v3.5.3-SURCyeoUl5S8FXxQle61/mode=imports/optimized/air-datepicker.js">
  <link rel="stylesheet" href="https://unpkg.com/air-datepicker@3.5.3/air-datepicker.css" type="text/css">

  <script type="module">
    import Datepicker from 'https://cdn.skypack.dev/pin/air-datepicker@v3.5.3-SURCyeoUl5S8FXxQle61/mode=imports/optimized/air-datepicker.js';
    
    const input = document.querySelector('input');
    const dp = new Datepicker(input);

    const button = document.querySelector('button');
    button.addEventListener('click', ()=>{

      console.log(`visible: ${dp.visible}`);
      console.log(`checkVisibility: ${dp.$datepicker.checkVisibility()}`);

      // Close datepicker if already open using `checkVisibility`.
      if (dp.$datepicker.checkVisibility()){
        input.blur();
        return;
      }

      // Close datepicker if already open using internal `visible` property.
      // if (dp.visible){
      //   input.blur();
      //   return;
      // }

      input.focus();
    });
    
  </script>
</head>
<body>
  <input>
  <button>X</button>
</body>
</html>
```

**Comment by t1m0n** [comment]
Why do you expect that? These things are not related to each other. You should use `visible` property to check is datepicker is visible or not.

**Comment by MagnusOxlund** [comment]
How are they unrelated?

From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/checkVisibility):

> The `checkVisibility()` method of the `[Element](https://developer.mozilla.org/en-US/docs/Web/API/Element)` interface checks whether the element is visible.

If the purpose of `visible` is not to report whether the calendar is visible (I'm borrowing the terminology from the docs to refer to the date picker dialog), maybe it would be good to specify that in the documentation.

**Comment by t1m0n** [comment]
This is because the `visible` property is set manually when the `hide` method is called, while the `checkVisibility()` checks the DOM/CSS properties. These two approaches can be different in some cases. For example, in your case, `visible` will be false because the datepicker has started to hide, but because it is still in the DOM (because of animation), the `checkVisibility()` function returns `true`.

**Comment by MagnusOxlund** [comment]
It sounds like we agree.

I understand if you don't want to change how `visible` works, but maybe it would be good to mention in the docs that it returns `false` while the element is still transitioning?
