### ISSUE TITLE
Keyboard navigation mode exits browser's fullscreen mode on Esc

### ISSUE THREAD

**Issue by MagnusOxlund** [t1m0n/air-datepicker#634]
Air Datepicker's [keyboard navigation mode](https://air-datepicker.com/docs#keyboardNav) will close an open calendar when the user hits the Esc key. The Esc key is also the default keyboard shortcut for exiting fullscreen mode on most browsers.

I would expect Air Datepicker to handle the conflict by suppressing the signal to exit fullscreen mode when there's a calendar open (e.g., `Event.preventDefault()`).

Tested with Air Datepicker 3.5.3 on Safari 17.6 and Firefox 130.0.1 on macOS 12.7.6.

**Comment by t1m0n** [comment]
It is a ver bad practice to change the default browser settings. However, there is no way to prevent a user from leaving full-screen mode.

**Comment by MagnusOxlund** [comment]
I'm not suggesting permanently disabling exiting fullscreen mode, just firing `event.preventDefault()` on a `keydown` event for the Esc key that's meant to close an open calendar dialog window when it's configured with the `keyboardNav` option.

Regarding changing browser defaults, you mgiht want to look at other libraries that do this, e.g., [Bootstrap](https://github.com/twbs/bootstrap/pull/22398).
