### ISSUE TITLE
How to access API for datepicker already initialised by a seperate script?

### ISSUE THREAD

**Issue by MezeDev** [t1m0n/air-datepicker#639]
I have a datepicker initialised by a script (`this.picker = new AirDatepicker(inputEl, options)`) 

I want to access the API for this datepicker but I dont have the variable (`this.picker`) that the datepicker was assigned to when it was created as that was in a different script.

I see in some old code examples the use of `$(element).data('datepicker')` but that doesnt seem to work - is there any way to get access to the API just by referencing the <input> element that was passed when initialising?

Thanks

**Comment by t1m0n** [comment]
Hello! There is no support for such feature currently. But you could add it by your own, you could do something like this - 
```javascript
const adp = new AirDatepicker(inputEl, options);
inputEl.adp = adp;

// Later you could call methods like this
inputEl.adp.selectDate('')
```

Maybe it would be a better option to have some global store where you can refer to a specific datepicker
