### ISSUE TITLE
Is there a way to destroy air-picker?

### ISSUE THREAD

**Issue by mkoczorowski** [t1m0n/air-datepicker#64]
Remove all listeners etc.. Quite useful when working with single page apps. Thanks

**Comment by t1m0n** [comment]
Yeah, there is `.destroy()` method for this:

```javascript
<input type="text"  />
<button id="destroy">Destroy</button>

<script>
var dp = $('input').datepicker().data('datepicker');

$('#destroy').on('click', function(){
    dp.destroy();
})
</script>
```

**Comment by mkoczorowski** [comment]
perfect! thanks :]

**Comment by arj060892** [comment]
Is their any way to reset the selected date

**Comment by nicooprat** [comment]
@arj060892 I think you're looking for the `clear()` method: http://t1m0n.name/air-datepicker/docs/#sub-section-50

@t1m0n is the `destroy()` method not described in the docs intentionally?

Looks like the div `.datepickers-container` is emptied but not removed from the DOM, is it the correct behavior?

**Comment by t1m0n** [comment]
@nicooprat oops, forgot to add description of `destroy` method, thanks for mentioning it ). What about container, actually didn't think about that, it remains invisible in any case, so it should not cause any problems.
