### ISSUE TITLE
Некорректная работа предустановленной кнопки 'clear' в версии 3.5.3

### ISSUE THREAD

**Issue by ksenofonus** [t1m0n/air-datepicker#642]
Здравствуйте! В версии 3.5.3, при нажатии кнопки "Очистить" если выбран диапазон дат сбрасываются только начальная и конечная дата, а сам диапазон между этими датами не сбрасывается (остается class -in-range-) .

**Comment by t1m0n** [comment]
Добрый день! спасибо большое за баг репорт, исправлю
