### ISSUE TITLE
Select  a single date when {range: true}   

### ISSUE THREAD

**Issue by arj060892** [t1m0n/air-datepicker#65]
I'm trying to integrate the datepicker into my app where user can select the dates within a range , but their are situations when user just need to check the data for one day only .

When i'm trying to select the same date again the text gets cleared up .

Is their any work around

**Comment by t1m0n** [comment]
I'm afraid there is no way to do it right now. Will try to add this feature in next release.

**Comment by howareyouo** [comment]
yes, i got the same problem !!

**Comment by t1m0n** [comment]
I've added this feature to [`develop`](https://github.com/t1m0n/air-datepicker/tree/develop) branch.Try to use it before main release is out.

**Comment by nicooprat** [comment]
Working great here ;) thanks.

**Comment by andresmorago** [comment]
hello. im curious about this feature. how can i use it?

**Comment by jon-mcclung-fortyau** [comment]
Was this functionality ever merged into main? It's not working for us.

**Comment by cbordon** [comment]
Hi all, this isn't so much a solution, but rather a work around.

Basically, if only one date is selected a button will pop up below the calendar.
By clicking the button it simply closes the calendar.

Now you will only have one date in your date input.

Without the button visually popping up, it is confusing for the user to know that they are allowed to just exit the calendar without selecting an end date and that is why I added a button that manually closes the calendar.

On your following page when you are reading the form data, just account for the fact that you only have one date and implement the logic as your app requires. e.g if end_date not set, end_date = start_date

In this code snippet, the button logic is just in the onShow and onSelect methods.

```
const datePicker = new AirDatepicker("#hero-datepicker", {
            locale: $locale,
            isMobile: true,
            range: true,
            multipleDatesSeparator: ' — ',
            autoClose: true,
            minDate: startPickerMin.toISODate(),
            maxDate: startPickerMax.toISODate(),
            onSelect: function(formattedDate, date) {
                const $closeButton = $('<button class="datepicker-close-button">Start and end dates are the same</button>');
                $('.air-datepicker .datepicker-close-button').remove(); // Remove existing close buttons
                if (datePicker.selectedDates.length == 1) {
                    $('.air-datepicker').append($closeButton);
                }
        
                $closeButton.on('click', () => {
                    datePicker.hide();
                });
            },
            onShow: function(formattedDate, date) {
                const $closeButton = $('<button class="datepicker-close-button">Start and end dates are the same</button>');
                $('.air-datepicker .datepicker-close-button').remove(); // Remove existing close buttons
                if (datePicker.selectedDates.length == 1) {
                    $('.air-datepicker').append($closeButton);
                }
        
                $closeButton.on('click', () => {
                    datePicker.hide();
                });
            }
        });
```
