### ISSUE TITLE
Ability to pre-select dates on initialise

### ISSUE THREAD

**Issue by b0gd4n** [t1m0n/air-datepicker#69]
Opening a datepicker field with dates already filled in does not pre-select the dates in the dropodown

**Comment by t1m0n** [comment]
There is no feature for serializing input value currently. You could you use `selectDate()` for pre selecting dates. #41

**Comment by nicooprat** [comment]
Was looking for this too. [`selectDate()`](http://t1m0n.name/air-datepicker/docs/#sub-section-48) takes a Date or **an array of Dates** as parameters. It also works with ranges the same way.

Working great, hope it will be the default behavior soon :)
