### ISSUE TITLE
Add onDropdown event

### ISSUE THREAD

**Issue by b0gd4n** [t1m0n/air-datepicker#71]
Ability to listed to datepicker open/dropdown event.

**Comment by t1m0n** [comment]
Added `onShow` `onHide` options

**Comment by joshua1** [comment]
will this work as ```data-on-show="onShowClick"``` given that events are defined as porperties when instantiating without the ```datepicker-here``` class definition

**Comment by t1m0n** [comment]
@joshua1 no, it will not work, because you can store only strings in data attributes and `onSelect` should be function.
