### ISSUE TITLE
Add selectMultipleDates() method

### ISSUE THREAD

**Issue by b0gd4n** [t1m0n/air-datepicker#72]
I am currently trying to make the range datepicker initialise with an existing input (eg date1 - date2).

Currently, the selectDate() method only takes one Date, not 2 for a range.

**Comment by t1m0n** [comment]
You could use `selectDate()` multiple times for selecting several dates, or you can pass an array of dates once:

```javascript
    var dp = $('#dp').datepicker({range: true}).data('datepicker');

   dp.selectDate(new Date(2016, 3, 18));
   dp.selectDate(new Date(2016, 3, 22));
```

OR

```javascript
    dp.selectDate([
        new Date(2016, 5, 10),
        new Date(2016, 5, 20)
    ]);
```

**Comment by b0gd4n** [comment]
Nice! That seems to be working nicely.

Thank you.
