### ISSUE TITLE
Ability to select date range on same day

### ISSUE THREAD

**Issue by b0gd4n** [t1m0n/air-datepicker#74]
Currently, I cannot select the end date range on the same day, a few hours later than the start date - it's minimum 1 day in-between,

**Comment by t1m0n** [comment]
You could try to use [`develop`](https://github.com/t1m0n/air-datepicker/tree/develop) branch, this feature is included there. #65

**Comment by b0gd4n** [comment]
nice, that works perfectly!
when should we expect the develop branch to be merged into master?

**Comment by b0gd4n** [comment]
any news on new update?

**Comment by t1m0n** [comment]
@b0gd4n hope soon

**Comment by t1m0n** [comment]
Done!

**Comment by praeligare** [comment]
Hi - this just happened to me. Am I missing something? Do i need to set any config anywhere for this to be enabled?

"air-datepicker": "^3.4.0",

**Comment by fulit103** [comment]
Hi [praeligare](https://github.com/praeligare), I had the same problem and I fixed using `toggleSelected` parameter:

```javascript
toggleSelected: ({ datepicker }) => {
        if (self.args.range == true) {
          if (datepicker.selectedDates.length == 2) {
            return true;
          }
          return false;
        }
        return true;
}
```

https://github.com/fulit103/ember-air-datepicker/pull/6/files
