### ISSUE TITLE
Button Today not working properly

### ISSUE THREAD

**Issue by dev4press** [t1m0n/air-datepicker#77]
When I add Today button, I expect that when I click this button, a current date/time is set and inserted. But, this button just returns the calendar to the page where the current date is, and I need to click on the date to set it. Why not make this working as it should: click on Today to set current date/time into the field.

**Comment by t1m0n** [comment]
There is option for that, please read docs carefully:

```javascript
// Select today
$('.datepicker').datepicker({
	todayButton: new Date()
})
```
