### ISSUE TITLE
Очистка выбранных данных

### ISSUE THREAD

**Issue by Maksim63** [t1m0n/air-datepicker#82]
Здравствуйте Тимофей.

есть несколько вопросов. код для примера. весь код и стили не привожу, для краткости.

```
<div id="myCalendar>
   <button type="button" id="dateaccept">OK</button>
</div>
  <span class="result"></span>

var Calendar = $('#myCalendar').datepicker({
    altField: "#view",
    altFieldDateFormat: "MM yyyy",
    view: "months",
    minView: "months",
    dateFormat: "MM yyyy",
    range: "true",
    multipleDatesSeparator: " - ",
    
    onSelect: function (fd) {
        var result = fd;
        $("#dateaccept").click(function(){
            $('.result').html(result);
        })
    }
})

```
календарь вызывается из модального окна, по нажатию на "ок" выбранные значения отрисовываются в .result. можно выбрать одну дату, можно диапазон. в данном случае я использую настройки для выбора месяцев. всё отображается хорошо. Но как только я пытаюсь отправить значение fd с помощью AJAX- запроса на сервер, то приходят две строки - отдельно первый выбранный месяц, и отдельно диапазон первый-последний месяц. 
1. как можно от этого избавится ? при этом на экран выводится всё отлично.
2. если без перезагрузки страницы вызвать календарь снова и выбрать ещё один диапазон - то на экарне выводится всё в порядке, в AJAX-запросе уже уходит 3 строки, предыдущие две и новая. как сделать очистку выбранных данных при каждом вызове календаря ?

**Comment by t1m0n** [comment]
Добрый день!
Скорее всего проблема в том, что вы каждый раз при выборе даты привязываете событие `click` на кнопку, из-за этого и получаются дубликаты. Если вы выберете три раза дату, то и событие `click` будет отрабатывать три раза вместо одного, и т.д. Тут лучше просто сохранять результат выбора во внешнюю переменную и уже с ней работать:

```javascript
<div id="myCalendar">
     <button type="button" id="dateaccept">OK</button>
</div>
<span class="result"></span>

var result = '';
var Calendar = $('#myCalendar').datepicker({
    altField: "#view",
    altFieldDateFormat: "MM yyyy",
    view: "months",
    minView: "months",
    dateFormat: "MM yyyy",
    range: "true",
    multipleDatesSeparator: " - ",
    onSelect: function (fd) {
        result = fd;
    }
});

$("#dateaccept").click(function(){
    $('.result').html(result);
})
```

Для того чтобы очистить выбранные даты есть метод `.clear()`:

```javascript

<div id="myCalendar">
     <button type="button" id="clear">Очистить</button>
</div>

var calendar = $('#myCalendar').datepicker().data('datepicker');

$('#clear').on('click', calendar.clear.bind(calendar));
