### ISSUE TITLE
onSelect не обрабатывает изменение времени

### ISSUE THREAD

**Issue by nvcenter** [t1m0n/air-datepicker#84]
При изменении времени в onSelect данные не передаются, верней данные передаются, только один раз. Пример:[https://jsfiddle.net/kb63adtz/]( https://jsfiddle.net/kb63adtz/)

**Comment by t1m0n** [comment]
В данном примере, в `.onSelect`, проверяется, не является ли выбранная дата равной предыдущей, поэтому при изменении времени функция срабатывает лишь один раз, потому что дата остается одинаковой. Чтобы этого избежать, просто уберите эту проверку, вот работающий пример - https://jsfiddle.net/kb63adtz/1/
