### ISSUE TITLE
Allow single date to be selected when using 'range'

### ISSUE THREAD

**Issue by kw7359** [t1m0n/air-datepicker#86]
When toggleSelected is set to False, it should allow you to select a single date along with a range, so for example, I could select 7/1/16 - 7/3/16 (regular range), or if I just wanted one date, the range feature would still work, but like this: 7/1/16 - 7/1/16

**Comment by t1m0n** [comment]
Its exactly how it works now. What is your problem?

**Comment by kw7359** [comment]
When I select a date and then click on it again to get the range (7/1/16 - 7/1/16)  the date is unselected.  If toggleSelected is set to False, clicking on the date again does nothing.

**Comment by t1m0n** [comment]
What version are you using? This feature is available since 2.1.0. I've created fiddle, try it out - https://jsfiddle.net/x47ptw8y/

**Comment by kw7359** [comment]
Where is the version identified?

    On Tuesday, July 19, 2016 1:12 AM, Timofey <notifications@github.com> wrote:
 

 What version are you using? This feature is available since 2.1.0. I've created fiddle, try it out - https://jsfiddle.net/x47ptw8y/—

**Comment by kw7359** [comment]
ok - I must have had an older version, because installing t he most recent files fixed the issue.  Thank you! 

    On Tuesday, July 19, 2016 9:36 AM, KEVIN WHITE <kevin_white@ameritech.net> wrote:
 

 Where is the version identified?

    On Tuesday, July 19, 2016 1:12 AM, Timofey <notifications@github.com> wrote:
 

 What version are you using? This feature is available since 2.1.0. I've created fiddle, try it out - https://jsfiddle.net/x47ptw8y/—

**Comment by t1m0n** [comment]
I'm afraid only place where is version now is `package.json` or `bower.json` in root folder.

**Comment by t1m0n** [comment]
Added `VERSION` property to plugin prototype.
