### ISSUE TITLE
Add option to have fixed height on calendar

### ISSUE THREAD

**Issue by gotsiy** [t1m0n/air-datepicker#87]
Добрый день!
Спасибо за отличный продукт!
Есть одно пожелание, могли бы Вы сделать так, что бы количество отображаемых дней было одинаковое.
Сейчас при переходе на разные месяцы отображается разное количество дней. Из-за этого меняется высота активного виджета. Но это как бы не проблема если виджет открывается вниз от текстового поля, но если виджет открывается вверх, то если меняется высота активного виджета, то он уменьшается вниз и строка навигации опускается вниз. Нужно менять положение курсора что бы опять попасть на навигацию.
Такой принцип постоянной высоты хорошо реализован в bootstrap-datepicker вот здесь:
https://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox

Успехов!
Сергей.

**Comment by t1m0n** [comment]
Добавлено в 3.5.0
