### ISSUE TITLE
Range active returns only one date object on select

### ISSUE THREAD

**Issue by mberhorst** [t1m0n/air-datepicker#9]
{Range: true} should return an array of date objects. Currently returns only one. I guess this is a bug.

Setting "multipleDates" to true brakes the UI when selecting a range.

**Comment by mberhorst** [comment]
I used the datePicker instance in the onSelect event to access the selectedDates. Works for me.

**Comment by t1m0n** [comment]
Fixed in develop branch, will be included in v1.2.1

**Comment by mberhorst** [comment]
Thanks a lot for your fast response. Great work. Keep it up.
