### ISSUE TITLE
Sync editable text field content with datepicker widget

### ISSUE THREAD

**Issue by modean** [t1m0n/air-datepicker#91]
If somebody types a date into the datepicker text field that has the datepicker widget associated, what is being typed does not sync with the widget. Only selecting something in the widget has an impact on the content in the text field.

This should work in both directions cause people have a tendency to do small changes directly in the text field rather than clicking through the calendar widget.

Setting the text field to read only is not an option.

**Comment by t1m0n** [comment]
There is already such issue - #41
