### ISSUE TITLE
Not showing default view after losing focus without selecting and date

### ISSUE THREAD

**Issue by francis6425** [t1m0n/air-datepicker#94]
If I set the view to 'days', when the user clicks thru to change the view to years but never select the date and lost focus, when the user click on it again, it will not revert back to the days view but follow the last view shown. Is it intended to be like this or can there be any option to make it always revert back to the original view after losing focus.

**Comment by t1m0n** [comment]
You can reset view manually by listening `blur` event, and setting desirable view after transition is completed:

**HTML**
```html
<input type="text" id="dp" />
```

**JS**
```javascript
var $input = $('#dp'),
    dp = $input.datepicker().data('datepicker');

$input.on('blur', function () {
    dp.$datepicker.one('transitionend', function () {
        dp.view = 'days';
    })
});
```

**Comment by t1m0n** [comment]
In new version you could also use `onHide` callback.
