### ISSUE TITLE
datepicker--content DIV not showing occasionally

### ISSUE THREAD

**Issue by jschaufele** [t1m0n/air-datepicker#98]
Found occasionally datepicker did not display -

adding "display:block!important" to the class below fixed this problem

.datepicker--content {
  box-sizing: content-box;
  padding: 4px;
    display: block!important;
}

**Comment by t1m0n** [comment]
Could you provide an example of when it happens?

**Comment by jschaufele** [comment]
have gotten past the issue but will recreate it - w/o the CSS update AND in one of my environments only the month div would show w/o any days beneath it - added the CSS above solved the issue - if you still would like a screen i'd be glad but it will take a couple days
