### ISSUE TITLE
Datepicker shows the wrong month in source code

### ISSUE THREAD

**Issue by paleacci** [t1m0n/air-datepicker#99]
Hi,

the data-month value is a number to small. This is the code for today:

<div class="datepicker--cell datepicker--cell-day -disabled-" data-date="1" data-month="7" data-year="2016">1</div>

data-month could be 8

best regards

**Comment by t1m0n** [comment]
Sorry, but I don't get what you want to say. Do you mean this `data-month` is smaller that should be? -
![data-month](https://cloud.githubusercontent.com/assets/1918251/17764515/8682130a-6528-11e6-9a71-00362be90bbf.png)
It's because of month number begins from 0.
